// This file is autogenerated by VESC Tool

#ifndef ER_QML_H_
#define ER_QML_H_

#include "datatypes.h"
#include <stdint.h>
#include <stdbool.h>

// Constants
#define DATA_QML_APP_SIZE		4394

// Variables
extern uint8_t data_qml_app[];

// ER_QML_H_
#endif
