// This file is autogenerated by VESC Tool

#ifndef QMLUI_EXAMPLE_HW_H_
#define QMLUI_EXAMPLE_HW_H_

#include "datatypes.h"
#include <stdint.h>
#include <stdbool.h>

// Constants
#define DATA_QML_HW_SIZE		1045

// Variables
extern uint8_t data_qml_hw[];

// QMLUI_EXAMPLE_HW_H_
#endif
