#!/bin/bash
set -e

make clean

mkdir -p build_all

################## HW 46 & 47 #######################

COPYDIR=build_all/46_o_47
mkdir $COPYDIR

# default
touch conf_general.h
make -j8 build_args="-DHW_VERSION_46"
cp build/BLDC_4_ChibiOS.bin $COPYDIR/VESC_default.bin

# 33k
touch conf_general.h
make -j8 build_args="-DVIN_R1=33000.0 -DHW_VERSION_46"
cp build/BLDC_4_ChibiOS.bin $COPYDIR/VESC_33k.bin

# 0005ohm
touch conf_general.h
make -j8 build_args="-DCURRENT_SHUNT_RES=0.0005 -DHW_VERSION_46"
cp build/BLDC_4_ChibiOS.bin $COPYDIR/VESC_0005ohm.bin

# ws2811
touch conf_general.h
make -j8 build_args="-DWS2811_ENABLE=1 -DHW_VERSION_46"
cp build/BLDC_4_ChibiOS.bin $COPYDIR/VESC_ws2811.bin

# ws2811_33k
touch conf_general.h
make -j8 build_args="-DWS2811_ENABLE=1 -DVIN_R1=33000.0 -DHW_VERSION_46"
cp build/BLDC_4_ChibiOS.bin $COPYDIR/VESC_ws2811_33k.bin

# servoout
touch conf_general.h
make -j8 build_args="-DSERVO_OUT_ENABLE=1 -DHW_VERSION_46"
cp build/BLDC_4_ChibiOS.bin $COPYDIR/VESC_servoout.bin

# Clean

rm -fR .dep build

#################### HW 48 ########################

COPYDIR=build_all/48
mkdir $COPYDIR

# default
touch conf_general.h
make -j8 build_args="-DHW_VERSION_48"
cp build/BLDC_4_ChibiOS.bin $COPYDIR/VESC_default.bin

# 0005ohm
touch conf_general.h
make -j8 build_args="-DCURRENT_SHUNT_RES=0.0005 -DHW_VERSION_48"
cp build/BLDC_4_ChibiOS.bin $COPYDIR/VESC_0005ohm.bin

# ws2811
touch conf_general.h
make -j8 build_args="-DWS2811_ENABLE=1 -DHW_VERSION_48"
cp build/BLDC_4_ChibiOS.bin $COPYDIR/VESC_ws2811.bin

# servoout
touch conf_general.h
make -j8 build_args="-DSERVO_OUT_ENABLE=1 -DHW_VERSION_48"
cp build/BLDC_4_ChibiOS.bin $COPYDIR/VESC_servoout.bin

# Clean

rm -fR .dep build

#################### HW 410 & 411 & 412 ########################

COPYDIR=build_all/410_o_411_o_412
mkdir $COPYDIR

# default
touch conf_general.h
make -j8 build_args="-DHW_VERSION_410"
cp build/BLDC_4_ChibiOS.bin $COPYDIR/VESC_default.bin

# default with HW limits disables
touch conf_general.h
make -j8 build_args="-DHW_VERSION_410 -DDISABLE_HW_LIMITS"
cp build/BLDC_4_ChibiOS.bin $COPYDIR/VESC_default_no_hw_limits.bin

# 0005ohm
touch conf_general.h
make -j8 build_args="-DCURRENT_SHUNT_RES=0.0005 -DHW_VERSION_410"
cp build/BLDC_4_ChibiOS.bin $COPYDIR/VESC_0005ohm.bin

# ws2811
touch conf_general.h
make -j8 build_args="-DWS2811_ENABLE=1 -DHW_VERSION_410"
cp build/BLDC_4_ChibiOS.bin $COPYDIR/VESC_ws2811.bin

# servoout
touch conf_general.h
make -j8 build_args="-DSERVO_OUT_ENABLE=1 -DHW_VERSION_410"
cp build/BLDC_4_ChibiOS.bin $COPYDIR/VESC_servoout.bin

# Clean

rm -fR .dep build

#################### HW 60 ########################

COPYDIR=build_all/60
mkdir $COPYDIR

# default
touch conf_general.h
make -j8 build_args="-DHW_VERSION_60"
cp build/BLDC_4_ChibiOS.bin $COPYDIR/VESC_default.bin

# default with HW limits disables
touch conf_general.h
make -j8 build_args="-DHW_VERSION_60 -DDISABLE_HW_LIMITS"
cp build/BLDC_4_ChibiOS.bin $COPYDIR/VESC_default_no_hw_limits.bin

# ws2811
touch conf_general.h
make -j8 build_args="-DWS2811_ENABLE=1 -DHW_VERSION_60"
cp build/BLDC_4_ChibiOS.bin $COPYDIR/VESC_ws2811.bin

# servoout
touch conf_general.h
make -j8 build_args="-DSERVO_OUT_ENABLE=1 -DHW_VERSION_60"
cp build/BLDC_4_ChibiOS.bin $COPYDIR/VESC_servoout.bin

# Clean

rm -fR .dep build

#################### HW DAS_RS ########################

COPYDIR=build_all/DAS_RS
mkdir $COPYDIR

# default
touch conf_general.h
make -j8 build_args="-DHW_VERSION_DAS_RS"
cp build/BLDC_4_ChibiOS.bin $COPYDIR/VESC_default.bin

# Clean

rm -fR .dep build

#################### HW 75_300 ########################

COPYDIR=build_all/75_300
mkdir $COPYDIR

# default
touch conf_general.h
make -j8 build_args="-DHW_VERSION_75_300"
cp build/BLDC_4_ChibiOS.bin $COPYDIR/VESC_default.bin

# default with HW limits disables
touch conf_general.h
make -j8 build_args="-DHW_VERSION_75_300 -DDISABLE_HW_LIMITS"
cp build/BLDC_4_ChibiOS.bin $COPYDIR/VESC_default_no_hw_limits.bin

# ws2811
touch conf_general.h
make -j8 build_args="-DWS2811_ENABLE=1 -DHW_VERSION_75_300"
cp build/BLDC_4_ChibiOS.bin $COPYDIR/VESC_ws2811.bin

# servoout
touch conf_general.h
make -j8 build_args="-DSERVO_OUT_ENABLE=1 -DHW_VERSION_75_300"
cp build/BLDC_4_ChibiOS.bin $COPYDIR/VESC_servoout.bin

# Clean

rm -fR .dep build

