
(define err1 'read_error)
(define err2 'type_error)
(define err3 'eval_error)
(define err4 'out_of_memory)
(define err5 'fatal_error)
(define err6 'out_of_stack)
(define err7 'division_by_zero)
(define err8 'variable_not_bound)

(define type1 'type-i)
(define type2 'type-u)
(define type3 'type-float)
(define type4 'type-list)
(define type5 'type-array)
(define type6 'type-symbol)

(defun main () {
       (if (and (eq err1 'read_error)
                (eq err2 'type_error)
                (eq err3 'eval_error)
                (eq err4 'out_of_memory)
                (eq err5 'fatal_error)
                (eq err6 'out_of_stack)
                (eq err7 'division_by_zero)
                (eq err8 'variable_not_bound)
                (eq type1 'type-i)
                (eq type2 'type-u)
                (eq type3 'type-float)
                (eq type4 'type-list)
                (eq type5 'type-array)
                (eq type6 'type-symbol))
           (print "SUCCESS")
           (print "FAILURE"))
       })

(image-save)
(fwrite-image (fopen "image.lbm" "w"))
