(send (self) 0)
(gc)
(send (self) 1)
(gc)
(send (self) 2)
(gc)
(send (self) 3)
(gc)
(send (self) 4)
(gc)
(send (self) 5)

(gc)

(check (and (= (recv ((? x) x)) 0)
            (= (recv ((? x) x)) 1)
            (= (recv ((? x) x)) 2)
            (= (recv ((? x) x)) 3)
            (= (recv ((? x) x)) 4)
            (= (recv ((? x) x)) 5)))
