// This file is autogenerated by VESC Tool

#ifndef QMLUI_LUNA_M600_H_
#define QMLUI_LUNA_M600_H_

#include "datatypes.h"
#include <stdint.h>
#include <stdbool.h>

// Constants
#define DATA_QML_HW_SIZE		6892

// Variables
extern uint8_t data_qml_hw[];

// QMLUI_LUNA_M600_H_
#endif
