
;; Deeply nested in body position. 75 levels deep.
(define r1 (let ((a1 10))
             (let ((a2 20))
               (let ((a3 30))
                 (let ((a4 40))
                   (let ((a5 50))
                     (let ((a6 60))
                       (let ((a7 70))
                         (let ((a8 80))
                           (let ((a9 90))
                             (let ((a10 100))
                               (let ((b1 10))
                                 (let ((b2 20))
                                   (let ((b3 30))
                                     (let ((b4 40))
                                       (let ((b5 50))
                                         (let ((b6 60))
                                           (let ((b7 70))
                                             (let ((b8 80))
                                               (let ((b9 90))
                                                 (let ((b10 100))
                                                   (let ((c1 10))
                                                     (let ((c2 20))
                                                       (let ((c3 30))
                                                         (let ((c4 40))
                                                           (let ((c5 50))
                                                             (let ((c6 60))
                                                               (let ((c7 70))
                                                                 (let ((c8 80))
                                                                   (let ((c9 90))
                                                                     (let ((c10 100))
                                                                       (let ((d1 10))
                                                                         (let ((d2 20))
                                                                           (let ((d3 30))
                                                                             (let ((d4 40))
                                                                               (let ((d5 50))
                                                                                 (let ((d6 60))
                                                                                   (let ((d7 70))
                                                                                     (let ((d8 80))
                                                                                       (let ((d9 90))
                                                                                         (let ((d10 100))
                                                                                           (let ((e1 10))
                                                                                             (let ((e2 20))
                                                                                               (let ((e3 30))
                                                                                                 (let ((e4 40))
                                                                                                   (let ((e5 50))
                                                                                                     (let ((e6 60))
                                                                                                       (let ((e7 70))
                                                                                                         (let ((e8 80))
                                                                                                           (let ((e9 90))
                                                                                                             (let ((e10 100))
                                                                                                               (let ((f1 10))
                                                                                                                 (let ((f2 20))
                                                                                                                   (let ((f3 30))
                                                                                                                     (let ((f4 40))
                                                                                                                       (let ((f5 50))
                                                                                                                         (let ((f6 60))
                                                                                                                           (let ((f7 70))
                                                                                                                             (let ((f8 80))
                                                                                                                               (let ((f9 90))
                                                                                                                                 (let ((f10 100))
                                                                                                                                   (let ((g1 10))
                                                                                                                                     (let ((g2 20))
                                                                                                                                       (let ((g3 30))
                                                                                                                                         (let ((g4 40))
                                                                                                                                           (let ((g5 50))
                                                                                                                                             (let ((g6 60))
                                                                                                                                               (let ((g7 70))
                                                                                                                                                 (let ((g8 80))
                                                                                                                                                   (let ((g9 90))
                                                                                                                                                     (let ((g10 100))
                                                                                                                                                       (let ((h1 10))
                                                                                                                                                         (let ((h2 20))
                                                                                                                                                           (let ((h3 30))
                                                                                                                                                             (let ((h4 40))
                                                                                                                                                               (let ((h5 50))
                                                                                                                                                                 (let ((r1 (+ a1 a2 a3 a4 a5 a6 a7 a8 a9 a10))
                                                                                                                                                                       (r2 (+ b1 b2 b3 b4 b5 b6 b7 b8 b9 b10))
                                                                                                                                                                       (r3 (+ c1 c2 c3 c4 c5 c6 c7 c8 c9 c10))
                                                                                                                                                                       (r4 (+ d1 d2 d3 d4 d5 d6 d7 d8 d9 d10))
                                                                                                                                                                       (r5 (+ e1 e2 e3 e4 e5 e6 e7 e8 e9 e10))
                                                                                                                                                                       (r6 (+ f1 f2 f3 f4 f5 f6 f7 f8 f9 f10))
                                                                                                                                                                       (r7 (+ g1 g2 g3 g4 g5 g6 g7 g8 g9 g10))
                                                                                                                                                                       (r8 (+ h1 h2 h3 h4 h5)))
                                                                                                                                                                   (+ r1 r2 r3 r4 r5 r6 r7 r8))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))

;; 7 chains of 10: 7*550=3850, 1 chain of 5: 150, total=4000
(define b1 (= r1 4000))

;; Deeply nested in body position with dependencies. 36 levels deep.

(define r2 (let ((a1 10))
             (let ((a2 (+ a1 10)))
               (let ((a3 (+ a2 10)))
                 (let ((a4 (+ a3 10)))
                   (let ((a5 (+ a4 10)))
                     (let ((a6 (+ a5 10)))
                       (let ((a7 (+ a6 10)))
                         (let ((a8 (+ a7 10)))
                           (let ((a9 (+ a8 10)))
                             (let ((b1 10))
                               (let ((b2 (+ b1 10)))
                                 (let ((b3 (+ b2 10)))
                                   (let ((b4 (+ b3 10)))
                                     (let ((b5 (+ b4 10)))
                                       (let ((b6 (+ b5 10)))
                                         (let ((b7 (+ b6 10)))
                                           (let ((b8 (+ b7 10)))
                                             (let ((b9 (+ b8 10)))
                                               (let ((c1 10))
                                                 (let ((c2 (+ c1 10)))
                                                   (let ((c3 (+ c2 10)))
                                                     (let ((c4 (+ c3 10)))
                                                       (let ((c5 (+ c4 10)))
                                                         (let ((c6 (+ c5 10)))
                                                           (let ((c7 (+ c6 10)))
                                                             (let ((c8 (+ c7 10)))
                                                               (let ((c9 (+ c8 10)))
                                                                 (let ((d1 10))
                                                                   (let ((d2 (+ d1 10)))
                                                                     (let ((d3 (+ d2 10)))
                                                                       (let ((d4 (+ d3 10)))
                                                                         (let ((d5 (+ d4 10)))
                                                                           (let ((d6 (+ d5 10)))
                                                                             (let ((d7 (+ d6 10)))
                                                                               (let ((d8 (+ d7 10)))
                                                                                 (let ((d9 (+ d8 10)))
                                                                                   (let ((r2 (+ a1 a2 a3 a4 a5 a6 a7 a8 a9))
                                                                                         (r3 (+ b1 b2 b3 b4 b5 b6 b7 b8 b9))
                                                                                         (r4 (+ c1 c2 c3 c4 c5 c6 c7 c8 c9))
                                                                                         (r5 (+ d1 d2 d3 d4 d5 d6 d7 d8 d9)))
                                                                                     (+ r2 r3 r4 r5)))))))))))))))))))))))))))))))))))))))

(define b2 (= r2 (* 4 450)))

;; Deeply nested and multiple bindings each level. 18 levels deep.

(define r3 (let ((a1 10)
                 (b1 10)
                 (c1 10)
                 (d1 10)
                 (e1 10))
             (let ((a2 (+ a1 10))
                   (b2 (+ b1 10))
                   (c2 (+ c1 10))
                   (d2 (+ d1 10))
                   (e2 (+ e1 10)))
               (let ((a3 (+ a2 10))
                     (b3 (+ b2 10))
                     (c3 (+ c2 10))
                     (d3 (+ d2 10))
                     (e3 (+ e2 10)))
                 (let ((a4 (+ a3 10))
                       (b4 (+ b3 10))
                       (c4 (+ c3 10))
                       (d4 (+ d3 10))
                       (e4 (+ e3 10)))
                   (let ((a5 (+ a4 10))
                         (b5 (+ b4 10))
                         (c5 (+ c4 10))
                         (d5 (+ d4 10))
                         (e5 (+ e4 10)))
                     (let ((a6 (+ a5 10))
                           (b6 (+ b5 10))
                           (c6 (+ c5 10))
                           (d6 (+ d5 10))
                           (e6 (+ e5 10)))
                       (let ((a7 (+ a6 10))
                             (b7 (+ b6 10))
                             (c7 (+ c6 10))
                             (d7 (+ d6 10))
                             (e7 (+ e6 10)))
                         (let ((a8 (+ a7 10))
                               (b8 (+ b7 10))
                               (c8 (+ c7 10))
                               (d8 (+ d7 10))
                               (e8 (+ e7 10)))
                           (let ((a9 (+ a8 10))
                                 (b9 (+ b8 10))
                                 (c9 (+ c8 10))
                                 (d9 (+ d8 10))
                                 (e9 (+ e8 10)))
                             (let ((a10 (+ a9 10))
                                   (b10 (+ b9 10))
                                   (c10 (+ c9 10))
                                   (d10 (+ d9 10))
                                   (e10 (+ e9 10)))
                               (let ((a11 (+ a10 10))
                                     (b11 (+ b10 10))
                                     (c11 (+ c10 10))
                                     (d11 (+ d10 10))
                                     (e11 (+ e10 10)))
                                 (let ((a12 (+ a11 10))
                                       (b12 (+ b11 10))
                                       (c12 (+ c11 10))
                                       (d12 (+ d11 10))
                                       (e12 (+ e11 10)))
                                   (let ((a13 (+ a12 10))
                                         (b13 (+ b12 10))
                                         (c13 (+ c12 10))
                                         (d13 (+ d12 10))
                                         (e13 (+ e12 10)))
                                     (let ((a14 (+ a13 10))
                                           (b14 (+ b13 10))
                                           (c14 (+ c13 10))
                                           (d14 (+ d13 10))
                                           (e14 (+ e13 10)))
                                       (let ((a15 (+ a14 10))
                                             (b15 (+ b14 10))
                                             (c15 (+ c14 10))
                                             (d15 (+ d14 10))
                                             (e15 (+ e14 10)))
                                         (let ((a16 (+ a15 10))
                                               (b16 (+ b15 10))
                                               (c16 (+ c15 10))
                                               (d16 (+ d15 10))
                                               (e16 (+ e15 10)))
                                           (let ((a17 (+ a16 10))
                                                 (b17 (+ b16 10))
                                                 (c17 (+ c16 10))
                                                 (d17 (+ d16 10))
                                                 (e17 (+ e16 10)))
                                             (let ((a18 (+ a17 10))
                                                   (b18 (+ b17 10))
                                                   (c18 (+ c17 10))
                                                   (d18 (+ d17 10))
                                                   (e18 (+ e17 10)))
                                               (let ((r1 (+ a1 a2 a3 a4 a5 a6 a7 a8 a9 a10 a11 a12 a13 a14 a15 a16 a17 a18))
                                                     (r2 (+ b1 b2 b3 b4 b5 b6 b7 b8 b9 b10 b11 b12 b13 b14 b15 b16 b17 b18))
                                                     (r3 (+ c1 c2 c3 c4 c5 c6 c7 c8 c9 c10 c11 c12 c13 c14 c15 c16 c17 c18))
                                                     (r4 (+ d1 d2 d3 d4 d5 d6 d7 d8 d9 d10 d11 d12 d13 d14 d15 d16 d17 d18))
                                                     (r5 (+ e1 e2 e3 e4 e5 e6 e7 e8 e9 e10 e11 e12 e13 e14 e15 e16 e17 e18)))
                                                 (+ r1 r2 r3 r4 r5)))))))))))))))))))))

;; Each chain: 10+20+...+180 = 10*(1+2+...+18) = 10*171 = 1710
;; 5 chains: 5 * 1710 = 8550
(define b3 (= r3 (* 5 1710)))

(if (and b1 b2 b3)
    (print "SUCCESS")
  (print "FAILURE"))
