
;; Deeply nested in body position.
(define r1 (let ((a1 10))
             (let ((a2 20))
               (let ((a3 30))
                 (let ((a4 40))
                   (let ((a5 50))
                     (let ((a6 60))
                       (let ((a7 70))
                         (let ((a8 80))
                           (let ((a9 90))
                             (let ((b1 10))
                               (let ((b2 20))
                                 (let ((b3 30))
                                   (let ((b4 40))
                                     (let ((b5 50))
                                       (let ((b6 60))
                                         (let ((b7 70))
                                           (let ((b8 80))
                                             (let ((b9 90))
                                               (let ((c1 10))
                                                 (let ((c2 20))
                                                   (let ((c3 30))
                                                     (let ((c4 40))
                                                       (let ((c5 50))
                                                         (let ((c6 60))
                                                           (let ((c7 70))
                                                             (let ((c8 80))
                                                               (let ((c9 90))
                                                                 (let ((d1 10))
                                                                   (let ((d2 20))
                                                                     (let ((d3 30))
                                                                       (let ((d4 40))
                                                                         (let ((d5 50))
                                                                           (let ((d6 60))
                                                                             (let ((d7 70))
                                                                               (let ((d8 80))
                                                                                 (let ((d9 90))
                                                                                   (let ((e1 10))
                                                                                     (let ((e2 20))
                                                                                       (let ((e3 30))
                                                                                         (let ((e4 40))
                                                                                           (let ((e5 50))
                                                                                             (let ((e6 60))
                                                                                               (let ((e7 70))
                                                                                                 (let ((e8 80))
                                                                                                   (let ((e9 90))
                                                                                                     (let ((r1 (+ a1 a2 a3 a4 a5 a6 a7 a8 a9))
                                                                                                           (r2 (+ b1 b2 b3 b4 b5 b6 b7 b8 b9))
                                                                                                           (r3 (+ c1 c2 c3 c4 c5 c6 c7 c8 c9))
                                                                                                           (r4 (+ d1 d2 d3 d4 d5 d6 d7 d8 d9))
                                                                                                           (r5 (+ e1 e2 e3 e4 e5 e6 e7 e8 e9)))
                                                                                                       (+ r1 r2 r3 r4 r5))))))))))))))))))))))))))))))))))))))))))))))))

                                                               
(define b1 (= r1 (* 5 450)))
                                       
;; Deeply nested in body position with dependencies

(define r2 (let ((a1 10))
             (let ((a2 (+ a1 10)))
               (let ((a3 (+ a2 10)))
                 (let ((a4 (+ a3 10)))
                   (let ((a5 (+ a4 10)))
                     (let ((a6 (+ a5 10)))
                       (let ((a7 (+ a6 10)))
                         (let ((a8 (+ a7 10)))
                           (let ((a9 (+ a8 10)))
                             (let ((b1 10))
                               (let ((b2 (+ b1 10)))
                                 (let ((b3 (+ b2 10)))
                                   (let ((b4 (+ b3 10)))
                                     (let ((b5 (+ b4 10)))
                                       (let ((b6 (+ b5 10)))
                                         (let ((b7 (+ b6 10)))
                                           (let ((b8 (+ b7 10)))
                                             (let ((b9 (+ b8 10)))
                                               (let ((r2 (+ a1 a2 a3 a4 a5 a6 a7 a8 a9))
                                                     (r3 (+ b1 b2 b3 b4 b5 b6 b7 b8 b9)))
                                                 (+ r2 r3)))))))))))))))))))))



(define b2 (= r2 (* 2 450)))

;; Deeply nested and multiple bindings each level

(define r3 (let ((a1 10)
                 (b1 10)
                 (c1 10)
                 (d1 10)
                 (e1 10))
             (let ((a2 (+ a1 10))
                   (b2 (+ b1 10))
                   (c2 (+ c1 10))
                   (d2 (+ d1 10))
                   (e2 (+ e1 10)))
               (let ((a3 (+ a2 10))
                     (b3 (+ b2 10))
                     (c3 (+ c2 10))
                     (d3 (+ d2 10))
                     (e3 (+ e2 10)))
                 (let ((a4 (+ a3 10))
                       (b4 (+ b3 10))
                       (c4 (+ c3 10))
                       (d4 (+ d3 10))
                       (e4 (+ e3 10)))
                   (let ((a5 (+ a4 10))
                         (b5 (+ b4 10))
                         (c5 (+ c4 10))
                         (d5 (+ d4 10))
                         (e5 (+ e4 10)))
                     (let ((a6 (+ a5 10))
                           (b6 (+ b5 10))
                           (c6 (+ c5 10))
                           (d6 (+ d5 10))
                           (e6 (+ e5 10)))
                       (let ((a7 (+ a6 10))
                             (b7 (+ b6 10))
                             (c7 (+ c6 10))
                             (d7 (+ d6 10))
                             (e7 (+ e6 10)))
                         (let ((a8 (+ a7 10))
                               (b8 (+ b7 10))
                               (c8 (+ c7 10))
                               (d8 (+ d7 10))
                               (e8 (+ e7 10)))
                           (let ((a9 (+ a8 10))
                                 (b9 (+ b8 10))
                                 (c9 (+ c8 10))
                                 (d9 (+ d8 10))
                                 (e9 (+ e8 10)))
                             (let ((r1 (+ a1 a2 a3 a4 a5 a6 a7 a8 a9))
                                   (r2 (+ b1 b2 b3 b4 b5 b6 b7 b8 b9))
                                   (r3 (+ c1 c2 c3 c4 c5 c6 c7 c8 c9))
                                   (r4 (+ d1 d2 d3 d4 d5 d6 d7 d8 d9))
                                   (r5 (+ e1 e2 e3 e4 e5 e6 e7 e8 e9)))
                               (+ r1 r2 r3 r4 r5))))))))))))

(print r3)
(define b3 (= r3 (* 5 450)))

(if (and b1 b2 b3)
    (print "SUCCESS")
  (print "FAILURE"))
