# This makefile assumes that you have "lbm" installed on your path. You can
# install it by running `make install` in ../repl.

all:
	lbm -H 10000000 --src="lbmref.lisp" --eval="(render-manual)" --terminate
