(send (self) 0)
(send (self) 1)
(send (self) 2)
(send (self) 3)
(send (self) 4)
(send (self) 5)
(send (self) 6)
(send (self) 7)
(send (self) 8)
(send (self) 9)
(send (self) 10)
(send (self) 11)
(send (self) 12)
(send (self) 13)
(send (self) 14)
(send (self) 15)
(send (self) 16)
(send (self) 17)

(check (and (= (recv ((? x) x)) 8)
            (= (recv ((? x) x)) 9)
            (= (recv ((? x) x)) 10)
            (= (recv ((? x) x)) 11)
            (= (recv ((? x) x)) 12)
            (= (recv ((? x) x)) 13)))
       
