// This file is autogenerated by VESC Tool

#ifndef QMLUI_LUNA_V1_H_
#define QMLUI_LUNA_V1_H_

#include "datatypes.h"
#include <stdint.h>
#include <stdbool.h>

// Constants
#define DATA_QML_APP_SIZE		7270

// Variables
extern uint8_t data_qml_app[];

// QMLUI_LUNA_V1_H_
#endif
