// This file is autogenerated by VESC Tool

#ifndef QMLUI_EXAMPLE_APP_H_
#define QMLUI_EXAMPLE_APP_H_

#include "datatypes.h"
#include <stdint.h>
#include <stdbool.h>

// Constants
#define DATA_QML_APP_SIZE		1632

// Variables
extern uint8_t data_qml_app[];

// QMLUI_EXAMPLE_APP_H_
#endif
