// This file is autogenerated by VESC Tool

#ifndef FINN_QML_H_
#define FINN_QML_H_

#include "datatypes.h"
#include <stdint.h>
#include <stdbool.h>

// Constants
#define DATA_QML_APP_SIZE		3103

// Variables
extern uint8_t data_qml_app[];

// FINN_QML_H_
#endif
