.TH "adc_config" 3 "Wed Sep 16 2015" "Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
adc_config \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <datatypes\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBadc_control_type\fP \fBctrl_type\fP"
.br
.ti -1c
.RI "float \fBhyst\fP"
.br
.ti -1c
.RI "float \fBvoltage_start\fP"
.br
.ti -1c
.RI "float \fBvoltage_end\fP"
.br
.ti -1c
.RI "bool \fBuse_filter\fP"
.br
.ti -1c
.RI "bool \fBsafe_start\fP"
.br
.ti -1c
.RI "bool \fBcc_button_inverted\fP"
.br
.ti -1c
.RI "bool \fBrev_button_inverted\fP"
.br
.ti -1c
.RI "bool \fBvoltage_inverted\fP"
.br
.ti -1c
.RI "float \fBrpm_lim_start\fP"
.br
.ti -1c
.RI "float \fBrpm_lim_end\fP"
.br
.ti -1c
.RI "bool \fBmulti_esc\fP"
.br
.ti -1c
.RI "bool \fBtc\fP"
.br
.ti -1c
.RI "float \fBtc_max_diff\fP"
.br
.ti -1c
.RI "uint32_t \fBupdate_rate_hz\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "bool cc_button_inverted"

.SS "\fBadc_control_type\fP ctrl_type"

.SS "float hyst"

.SS "bool multi_esc"

.SS "bool rev_button_inverted"

.SS "float rpm_lim_end"

.SS "float rpm_lim_start"

.SS "bool safe_start"

.SS "bool tc"

.SS "float tc_max_diff"

.SS "uint32_t update_rate_hz"

.SS "bool use_filter"

.SS "float voltage_end"

.SS "bool voltage_inverted"

.SS "float voltage_start"


.SH "Author"
.PP 
Generated automatically by Doxygen from the source code\&.
