.TH "applications/app.h" 3 "Wed Sep 16 2015" "Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
applications/app.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'conf_general\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBapp_init\fP (\fBapp_configuration\fP *conf)"
.br
.ti -1c
.RI "const \fBapp_configuration\fP * \fBapp_get_configuration\fP (void)"
.br
.ti -1c
.RI "void \fBapp_set_configuration\fP (\fBapp_configuration\fP *conf)"
.br
.ti -1c
.RI "void \fBapp_ppm_start\fP (void)"
.br
.ti -1c
.RI "void \fBapp_ppm_configure\fP (\fBppm_config\fP *conf)"
.br
.ti -1c
.RI "void \fBapp_adc_start\fP (bool use_rx_tx)"
.br
.ti -1c
.RI "void \fBapp_adc_configure\fP (\fBadc_config\fP *conf)"
.br
.ti -1c
.RI "float \fBapp_adc_get_decoded_level\fP (void)"
.br
.ti -1c
.RI "float \fBapp_adc_get_voltage\fP (void)"
.br
.ti -1c
.RI "void \fBapp_uartcomm_start\fP (void)"
.br
.ti -1c
.RI "void \fBapp_uartcomm_configure\fP (uint32_t baudrate)"
.br
.ti -1c
.RI "void \fBapp_nunchuk_start\fP (void)"
.br
.ti -1c
.RI "void \fBapp_nunchuk_configure\fP (\fBchuk_config\fP *conf)"
.br
.ti -1c
.RI "float \fBapp_nunchuk_get_decoded_chuk\fP (void)"
.br
.ti -1c
.RI "void \fBapp_nunchuk_update_output\fP (\fBchuck_data\fP *data)"
.br
.ti -1c
.RI "void \fBapp_gurgalof_init\fP (void)"
.br
.ti -1c
.RI "void \fBapp_sten_init\fP (void)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void app_adc_configure (\fBadc_config\fP * conf)"

.SS "float app_adc_get_decoded_level (void)"

.SS "float app_adc_get_voltage (void)"

.SS "void app_adc_start (bool use_rx_tx)"

.SS "const \fBapp_configuration\fP* app_get_configuration (void)"

.SS "void app_gurgalof_init (void)"

.SS "void app_init (\fBapp_configuration\fP * conf)"

.SS "void app_nunchuk_configure (\fBchuk_config\fP * conf)"

.SS "float app_nunchuk_get_decoded_chuk (void)"

.SS "void app_nunchuk_start (void)"

.SS "void app_nunchuk_update_output (\fBchuck_data\fP * data)"

.SS "void app_ppm_configure (\fBppm_config\fP * conf)"

.SS "void app_ppm_start (void)"

.SS "void app_set_configuration (\fBapp_configuration\fP * conf)"
Reconfigure all apps\&. Note that this will not start apps that are not already running, that should be done at boot\&. Some apps don't have any configuration options\&.
.PP
\fBParameters:\fP
.RS 4
\fIconf\fP The new configuration to use\&. 
.RE
.PP

.SS "void app_sten_init (void)"

.SS "void app_uartcomm_configure (uint32_t baudrate)"

.SS "void app_uartcomm_start (void)"

.SH "Author"
.PP 
Generated automatically by Doxygen from the source code\&.
