.TH "applications/app.c" 3 "Wed Sep 16 2015" "Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
applications/app.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'app\&.h'\fP
.br
\fC#include 'ch\&.h'\fP
.br
\fC#include 'hal\&.h'\fP
.br
\fC#include 'hw\&.h'\fP
.br
\fC#include 'nrf_driver\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBapp_init\fP (\fBapp_configuration\fP *conf)"
.br
.ti -1c
.RI "const \fBapp_configuration\fP * \fBapp_get_configuration\fP (void)"
.br
.ti -1c
.RI "void \fBapp_set_configuration\fP (\fBapp_configuration\fP *conf)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "const \fBapp_configuration\fP* app_get_configuration (void)"

.SS "void app_init (\fBapp_configuration\fP * conf)"

.SS "void app_set_configuration (\fBapp_configuration\fP * conf)"
Reconfigure all apps\&. Note that this will not start apps that are not already running, that should be done at boot\&. Some apps don't have any configuration options\&.
.PP
\fBParameters:\fP
.RS 4
\fIconf\fP The new configuration to use\&. 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen from the source code\&.
