.TH "applications/app_ppm.c" 3 "Wed Sep 16 2015" "Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
applications/app_ppm.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'app\&.h'\fP
.br
\fC#include 'ch\&.h'\fP
.br
\fC#include 'hal\&.h'\fP
.br
\fC#include 'stm32f4xx_conf\&.h'\fP
.br
\fC#include 'servo_dec\&.h'\fP
.br
\fC#include 'mcpwm\&.h'\fP
.br
\fC#include 'timeout\&.h'\fP
.br
\fC#include 'utils\&.h'\fP
.br
\fC#include 'comm_can\&.h'\fP
.br
\fC#include <math\&.h>\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBMAX_CAN_AGE\fP   0\&.1"
.br
.ti -1c
.RI "#define \fBMIN_PULSES_WITHOUT_POWER\fP   50"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBapp_ppm_configure\fP (\fBppm_config\fP *conf)"
.br
.ti -1c
.RI "void \fBapp_ppm_start\fP (void)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "VirtualTimer \fBvt\fP"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define MAX_CAN_AGE   0\&.1"

.SS "#define MIN_PULSES_WITHOUT_POWER   50"

.SH "Function Documentation"
.PP 
.SS "void app_ppm_configure (\fBppm_config\fP * conf)"

.SS "void app_ppm_start (void)"

.SH "Variable Documentation"
.PP 
.SS "VirtualTimer vt"

.SH "Author"
.PP 
Generated automatically by Doxygen from the source code\&.
