.TH "applications/app_nunchuk.c" 3 "Wed Sep 16 2015" "Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
applications/app_nunchuk.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'app\&.h'\fP
.br
\fC#include 'ch\&.h'\fP
.br
\fC#include 'hal\&.h'\fP
.br
\fC#include 'hw\&.h'\fP
.br
\fC#include 'mcpwm\&.h'\fP
.br
\fC#include 'commands\&.h'\fP
.br
\fC#include 'utils\&.h'\fP
.br
\fC#include 'timeout\&.h'\fP
.br
\fC#include <string\&.h>\fP
.br
\fC#include <math\&.h>\fP
.br
\fC#include 'led_external\&.h'\fP
.br
\fC#include 'datatypes\&.h'\fP
.br
\fC#include 'comm_can\&.h'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBOUTPUT_ITERATION_TIME_MS\fP   1"
.br
.ti -1c
.RI "#define \fBMAX_CURR_DIFFERENCE\fP   5\&.0"
.br
.ti -1c
.RI "#define \fBMAX_CAN_AGE\fP   0\&.1"
.br
.ti -1c
.RI "#define \fBRPM_FILTER_SAMPLES\fP   8"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBapp_nunchuk_configure\fP (\fBchuk_config\fP *conf)"
.br
.ti -1c
.RI "void \fBapp_nunchuk_start\fP (void)"
.br
.ti -1c
.RI "float \fBapp_nunchuk_get_decoded_chuk\fP (void)"
.br
.ti -1c
.RI "void \fBapp_nunchuk_update_output\fP (\fBchuck_data\fP *data)"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define MAX_CAN_AGE   0\&.1"

.SS "#define MAX_CURR_DIFFERENCE   5\&.0"

.SS "#define OUTPUT_ITERATION_TIME_MS   1"

.SS "#define RPM_FILTER_SAMPLES   8"

.SH "Function Documentation"
.PP 
.SS "void app_nunchuk_configure (\fBchuk_config\fP * conf)"

.SS "float app_nunchuk_get_decoded_chuk (void)"

.SS "void app_nunchuk_start (void)"

.SS "void app_nunchuk_update_output (\fBchuck_data\fP * data)"

.SH "Author"
.PP 
Generated automatically by Doxygen from the source code\&.
