.TH "app_configuration" 3 "Wed Sep 16 2015" "Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
app_configuration \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <datatypes\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "uint8_t \fBcontroller_id\fP"
.br
.ti -1c
.RI "uint32_t \fBtimeout_msec\fP"
.br
.ti -1c
.RI "float \fBtimeout_brake_current\fP"
.br
.ti -1c
.RI "bool \fBsend_can_status\fP"
.br
.ti -1c
.RI "uint32_t \fBsend_can_status_rate_hz\fP"
.br
.ti -1c
.RI "\fBapp_use\fP \fBapp_to_use\fP"
.br
.ti -1c
.RI "\fBppm_config\fP \fBapp_ppm_conf\fP"
.br
.ti -1c
.RI "\fBadc_config\fP \fBapp_adc_conf\fP"
.br
.ti -1c
.RI "uint32_t \fBapp_uart_baudrate\fP"
.br
.ti -1c
.RI "\fBchuk_config\fP \fBapp_chuk_conf\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "\fBadc_config\fP app_adc_conf"

.SS "\fBchuk_config\fP app_chuk_conf"

.SS "\fBppm_config\fP app_ppm_conf"

.SS "\fBapp_use\fP app_to_use"

.SS "uint32_t app_uart_baudrate"

.SS "uint8_t controller_id"

.SS "bool send_can_status"

.SS "uint32_t send_can_status_rate_hz"

.SS "float timeout_brake_current"

.SS "uint32_t timeout_msec"


.SH "Author"
.PP 
Generated automatically by Doxygen from the source code\&.
