.TH "applications/app_uartcomm.c" 3 "Wed Sep 16 2015" "Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
applications/app_uartcomm.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'app\&.h'\fP
.br
\fC#include 'ch\&.h'\fP
.br
\fC#include 'hal\&.h'\fP
.br
\fC#include 'hw\&.h'\fP
.br
\fC#include 'mcpwm\&.h'\fP
.br
\fC#include 'packet\&.h'\fP
.br
\fC#include 'commands\&.h'\fP
.br
\fC#include <string\&.h>\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBBAUDRATE\fP   115200"
.br
.ti -1c
.RI "#define \fBPACKET_HANDLER\fP   1"
.br
.ti -1c
.RI "#define \fBSERIAL_RX_BUFFER_SIZE\fP   1024"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBapp_uartcomm_start\fP (void)"
.br
.ti -1c
.RI "void \fBapp_uartcomm_configure\fP (uint32_t baudrate)"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define BAUDRATE   115200"

.SS "#define PACKET_HANDLER   1"

.SS "#define SERIAL_RX_BUFFER_SIZE   1024"

.SH "Function Documentation"
.PP 
.SS "void app_uartcomm_configure (uint32_t baudrate)"

.SS "void app_uartcomm_start (void)"

.SH "Author"
.PP 
Generated automatically by Doxygen from the source code\&.
