.TH "applications/app_adc.c" 3 "Wed Sep 16 2015" "Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
applications/app_adc.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'app\&.h'\fP
.br
\fC#include 'ch\&.h'\fP
.br
\fC#include 'hal\&.h'\fP
.br
\fC#include 'stm32f4xx_conf\&.h'\fP
.br
\fC#include 'mcpwm\&.h'\fP
.br
\fC#include 'timeout\&.h'\fP
.br
\fC#include 'utils\&.h'\fP
.br
\fC#include 'comm_can\&.h'\fP
.br
\fC#include 'hw\&.h'\fP
.br
\fC#include <math\&.h>\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBMAX_CAN_AGE\fP   0\&.1"
.br
.ti -1c
.RI "#define \fBMIN_MS_WITHOUT_POWER\fP   500"
.br
.ti -1c
.RI "#define \fBFILTER_SAMPLES\fP   5"
.br
.ti -1c
.RI "#define \fBRPM_FILTER_SAMPLES\fP   8"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBapp_adc_configure\fP (\fBadc_config\fP *conf)"
.br
.ti -1c
.RI "void \fBapp_adc_start\fP (bool use_rx_tx)"
.br
.ti -1c
.RI "float \fBapp_adc_get_decoded_level\fP (void)"
.br
.ti -1c
.RI "float \fBapp_adc_get_voltage\fP (void)"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define FILTER_SAMPLES   5"

.SS "#define MAX_CAN_AGE   0\&.1"

.SS "#define MIN_MS_WITHOUT_POWER   500"

.SS "#define RPM_FILTER_SAMPLES   8"

.SH "Function Documentation"
.PP 
.SS "void app_adc_configure (\fBadc_config\fP * conf)"

.SS "float app_adc_get_decoded_level (void)"

.SS "float app_adc_get_voltage (void)"

.SS "void app_adc_start (bool use_rx_tx)"

.SH "Author"
.PP 
Generated automatically by Doxygen from the source code\&.
