.TH "can_status_msg" 3 "Wed Sep 16 2015" "Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
can_status_msg \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <datatypes\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBid\fP"
.br
.ti -1c
.RI "systime_t \fBrx_time\fP"
.br
.ti -1c
.RI "float \fBrpm\fP"
.br
.ti -1c
.RI "float \fBcurrent\fP"
.br
.ti -1c
.RI "float \fBduty\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "float current"

.SS "float duty"

.SS "int id"

.SS "float rpm"

.SS "systime_t rx_time"


.SH "Author"
.PP 
Generated automatically by Doxygen from the source code\&.
