.TH "chconf.h" 3 "Wed Sep 16 2015" "Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
chconf.h \- 
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBCHPRINTF_USE_FLOAT\fP   TRUE"
.br
.ti -1c
.RI "#define \fBCORTEX_SIMPLIFIED_PRIORITY\fP   TRUE"
.br
.ti -1c
.RI "#define \fBPORT_IDLE_THREAD_STACK_SIZE\fP   64"
.br
.ti -1c
.RI "#define \fBPORT_INT_REQUIRED_STACK\fP   128"
.br
.in -1c
.PP
.RI "\fBKernel parameters and options\fP"
.br

.in +1c
.in +1c
.ti -1c
.RI "#define \fBCH_FREQUENCY\fP   10000"
.br
.RI "\fISystem tick frequency\&. \fP"
.ti -1c
.RI "#define \fBCH_TIME_QUANTUM\fP   4"
.br
.RI "\fIRound robin interval\&. \fP"
.ti -1c
.RI "#define \fBCH_MEMCORE_SIZE\fP   0"
.br
.RI "\fIManaged RAM size\&. \fP"
.ti -1c
.RI "#define \fBCH_NO_IDLE_THREAD\fP   FALSE"
.br
.RI "\fIIdle thread automatic spawn suppression\&. \fP"
.in -1c
.in -1c
.PP
.RI "\fBPerformance options\fP"
.br

.in +1c
.in +1c
.ti -1c
.RI "#define \fBCH_OPTIMIZE_SPEED\fP   TRUE"
.br
.RI "\fIOS optimization\&. \fP"
.in -1c
.in -1c
.PP
.RI "\fBSubsystem options\fP"
.br

.in +1c
.in +1c
.ti -1c
.RI "#define \fBCH_USE_REGISTRY\fP   TRUE"
.br
.RI "\fIThreads registry APIs\&. \fP"
.ti -1c
.RI "#define \fBCH_USE_WAITEXIT\fP   TRUE"
.br
.RI "\fIThreads synchronization APIs\&. \fP"
.ti -1c
.RI "#define \fBCH_USE_SEMAPHORES\fP   TRUE"
.br
.RI "\fISemaphores APIs\&. \fP"
.ti -1c
.RI "#define \fBCH_USE_SEMAPHORES_PRIORITY\fP   FALSE"
.br
.RI "\fISemaphores queuing mode\&. \fP"
.ti -1c
.RI "#define \fBCH_USE_SEMSW\fP   TRUE"
.br
.RI "\fIAtomic semaphore API\&. \fP"
.ti -1c
.RI "#define \fBCH_USE_MUTEXES\fP   TRUE"
.br
.RI "\fIMutexes APIs\&. \fP"
.ti -1c
.RI "#define \fBCH_USE_CONDVARS\fP   TRUE"
.br
.RI "\fIConditional Variables APIs\&. \fP"
.ti -1c
.RI "#define \fBCH_USE_CONDVARS_TIMEOUT\fP   TRUE"
.br
.RI "\fIConditional Variables APIs with timeout\&. \fP"
.ti -1c
.RI "#define \fBCH_USE_EVENTS\fP   TRUE"
.br
.RI "\fIEvents Flags APIs\&. \fP"
.ti -1c
.RI "#define \fBCH_USE_EVENTS_TIMEOUT\fP   TRUE"
.br
.RI "\fIEvents Flags APIs with timeout\&. \fP"
.ti -1c
.RI "#define \fBCH_USE_MESSAGES\fP   TRUE"
.br
.RI "\fISynchronous Messages APIs\&. \fP"
.ti -1c
.RI "#define \fBCH_USE_MESSAGES_PRIORITY\fP   FALSE"
.br
.RI "\fISynchronous Messages queuing mode\&. \fP"
.ti -1c
.RI "#define \fBCH_USE_MAILBOXES\fP   TRUE"
.br
.RI "\fIMailboxes APIs\&. \fP"
.ti -1c
.RI "#define \fBCH_USE_QUEUES\fP   TRUE"
.br
.RI "\fII/O Queues APIs\&. \fP"
.ti -1c
.RI "#define \fBCH_USE_MEMCORE\fP   TRUE"
.br
.RI "\fICore Memory Manager APIs\&. \fP"
.ti -1c
.RI "#define \fBCH_USE_HEAP\fP   TRUE"
.br
.RI "\fIHeap Allocator APIs\&. \fP"
.ti -1c
.RI "#define \fBCH_USE_MALLOC_HEAP\fP   FALSE"
.br
.RI "\fIC-runtime allocator\&. \fP"
.ti -1c
.RI "#define \fBCH_USE_MEMPOOLS\fP   TRUE"
.br
.RI "\fIMemory Pools Allocator APIs\&. \fP"
.ti -1c
.RI "#define \fBCH_USE_DYNAMIC\fP   TRUE"
.br
.RI "\fIDynamic Threads APIs\&. \fP"
.in -1c
.in -1c
.PP
.RI "\fBDebug options\fP"
.br

.in +1c
.in +1c
.ti -1c
.RI "#define \fBCH_DBG_SYSTEM_STATE_CHECK\fP   FALSE"
.br
.RI "\fIDebug option, system state check\&. \fP"
.ti -1c
.RI "#define \fBCH_DBG_ENABLE_CHECKS\fP   FALSE"
.br
.RI "\fIDebug option, parameters checks\&. \fP"
.ti -1c
.RI "#define \fBCH_DBG_ENABLE_ASSERTS\fP   FALSE"
.br
.RI "\fIDebug option, consistency checks\&. \fP"
.ti -1c
.RI "#define \fBCH_DBG_ENABLE_TRACE\fP   FALSE"
.br
.RI "\fIDebug option, trace buffer\&. \fP"
.ti -1c
.RI "#define \fBCH_DBG_ENABLE_STACK_CHECK\fP   FALSE"
.br
.RI "\fIDebug option, stack checks\&. \fP"
.ti -1c
.RI "#define \fBCH_DBG_FILL_THREADS\fP   FALSE"
.br
.RI "\fIDebug option, stacks initialization\&. \fP"
.ti -1c
.RI "#define \fBCH_DBG_THREADS_PROFILING\fP   TRUE"
.br
.RI "\fIDebug option, threads profiling\&. \fP"
.in -1c
.in -1c
.PP
.RI "\fBKernel hooks\fP"
.br

.in +1c
.in +1c
.ti -1c
.RI "#define \fBTHREAD_EXT_FIELDS\fP   /* Add threads custom fields here\&.*/"
.br
.RI "\fIThreads descriptor structure extension\&. \fP"
.ti -1c
.RI "#define \fBTHREAD_EXT_INIT_HOOK\fP(tp)"
.br
.RI "\fIThreads initialization hook\&. \fP"
.ti -1c
.RI "#define \fBTHREAD_EXT_EXIT_HOOK\fP(tp)"
.br
.RI "\fIThreads finalization hook\&. \fP"
.ti -1c
.RI "#define \fBTHREAD_CONTEXT_SWITCH_HOOK\fP(ntp,  otp)"
.br
.RI "\fIContext switch hook\&. \fP"
.ti -1c
.RI "#define \fBIDLE_LOOP_HOOK\fP()"
.br
.RI "\fIIdle Loop hook\&. \fP"
.ti -1c
.RI "#define \fBSYSTEM_TICK_EVENT_HOOK\fP()"
.br
.RI "\fISystem tick event hook\&. \fP"
.ti -1c
.RI "#define \fBSYSTEM_HALT_HOOK\fP()"
.br
.RI "\fISystem halt hook\&. \fP"
.in -1c
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen from the source code\&.
