.TH "chuck_data" 3 "Wed Sep 16 2015" "Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
chuck_data \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <datatypes\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBjs_x\fP"
.br
.ti -1c
.RI "int \fBjs_y\fP"
.br
.ti -1c
.RI "int \fBacc_x\fP"
.br
.ti -1c
.RI "int \fBacc_y\fP"
.br
.ti -1c
.RI "int \fBacc_z\fP"
.br
.ti -1c
.RI "bool \fBbt_c\fP"
.br
.ti -1c
.RI "bool \fBbt_z\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "int acc_x"

.SS "int acc_y"

.SS "int acc_z"

.SS "bool bt_c"

.SS "bool bt_z"

.SS "int js_x"

.SS "int js_y"


.SH "Author"
.PP 
Generated automatically by Doxygen from the source code\&.
