.TH "chuk_config" 3 "Wed Sep 16 2015" "Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
chuk_config \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <datatypes\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBchuk_control_type\fP \fBctrl_type\fP"
.br
.ti -1c
.RI "float \fBhyst\fP"
.br
.ti -1c
.RI "float \fBrpm_lim_start\fP"
.br
.ti -1c
.RI "float \fBrpm_lim_end\fP"
.br
.ti -1c
.RI "float \fBramp_time_pos\fP"
.br
.ti -1c
.RI "float \fBramp_time_neg\fP"
.br
.ti -1c
.RI "bool \fBmulti_esc\fP"
.br
.ti -1c
.RI "bool \fBtc\fP"
.br
.ti -1c
.RI "float \fBtc_max_diff\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "\fBchuk_control_type\fP ctrl_type"

.SS "float hyst"

.SS "bool multi_esc"

.SS "float ramp_time_neg"

.SS "float ramp_time_pos"

.SS "float rpm_lim_end"

.SS "float rpm_lim_start"

.SS "bool tc"

.SS "float tc_max_diff"


.SH "Author"
.PP 
Generated automatically by Doxygen from the source code\&.
