.TH "commands.h" 3 "Wed Sep 16 2015" "Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
commands.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'datatypes\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBcommands_init\fP (void)"
.br
.ti -1c
.RI "void \fBcommands_set_send_func\fP (void(*func)(unsigned char *data, unsigned int len))"
.br
.ti -1c
.RI "void \fBcommands_send_packet\fP (unsigned char *data, unsigned int len)"
.br
.ti -1c
.RI "void \fBcommands_process_packet\fP (unsigned char *data, unsigned int len)"
.br
.ti -1c
.RI "void \fBcommands_printf\fP (char *format,\&.\&.\&.)"
.br
.ti -1c
.RI "void \fBcommands_send_samples\fP (uint8_t *data, int len)"
.br
.ti -1c
.RI "void \fBcommands_send_rotor_pos\fP (float rotor_pos)"
.br
.ti -1c
.RI "void \fBcommands_send_experiment_samples\fP (float *samples, int len)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void commands_init (void)"

.SS "void commands_printf (char * format,  \&.\&.\&.)"

.SS "void commands_process_packet (unsigned char * data, unsigned int len)"
Process a received buffer with commands and data\&.
.PP
\fBParameters:\fP
.RS 4
\fIdata\fP The buffer to process\&.
.br
\fIlen\fP The length of the buffer\&. 
.RE
.PP

.SS "void commands_send_experiment_samples (float * samples, int len)"

.SS "void commands_send_packet (unsigned char * data, unsigned int len)"
Send a packet using the set send function\&.
.PP
\fBParameters:\fP
.RS 4
\fIdata\fP The packet data\&.
.br
\fIlen\fP The data length\&. 
.RE
.PP

.SS "void commands_send_rotor_pos (float rotor_pos)"

.SS "void commands_send_samples (uint8_t * data, int len)"

.SS "void commands_set_send_func (void(*)(unsigned char *data, unsigned int len) func)"
Provide a function to use the next time there are packets to be sent\&.
.PP
\fBParameters:\fP
.RS 4
\fIfunc\fP A pointer to the packet sending function\&. 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen from the source code\&.
