.TH "EEPROM_Emulation" 3 "Wed Sep 16 2015" "Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
EEPROM_Emulation \- EEPROM_Emulation
.SS "Functions"

.in +1c
.ti -1c
.RI "uint16_t \fBEE_Init\fP (void)"
.br
.RI "\fIRestore the pages to a known good state in case of page's status corruption after a power loss\&. \fP"
.ti -1c
.RI "uint16_t \fBEE_ReadVariable\fP (uint16_t VirtAddress, uint16_t *Data)"
.br
.RI "\fIReturns the last stored variable data, if found, which correspond to the passed virtual address\&. \fP"
.ti -1c
.RI "uint16_t \fBEE_WriteVariable\fP (uint16_t VirtAddress, uint16_t Data)"
.br
.RI "\fIWrites/upadtes variable data in EEPROM\&. \fP"
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "uint16_t \fBDataVar\fP = 0"
.br
.ti -1c
.RI "uint16_t \fBVirtAddVarTab\fP [\fBNB_OF_VAR\fP]"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SH "Function Documentation"
.PP 
.SS "uint16_t EE_Init (void)"

.PP
Restore the pages to a known good state in case of page's status corruption after a power loss\&. 
.PP
\fBParameters:\fP
.RS 4
\fINone\&.\fP 
.RE
.PP
\fBReturn values:\fP
.RS 4
\fI-\fP Flash error code: on write Flash error
.IP "\(bu" 2
FLASH_COMPLETE: on success 
.PP
.RE
.PP

.SS "uint16_t EE_ReadVariable (uint16_t VirtAddress, uint16_t * Data)"

.PP
Returns the last stored variable data, if found, which correspond to the passed virtual address\&. 
.PP
\fBParameters:\fP
.RS 4
\fIVirtAddress\fP Variable virtual address 
.br
\fIData\fP Global variable contains the read variable value 
.RE
.PP
\fBReturn values:\fP
.RS 4
\fISuccess\fP or error status:
.IP "\(bu" 2
0: if variable was found
.IP "\(bu" 2
1: if the variable was not found
.IP "\(bu" 2
NO_VALID_PAGE: if no valid page was found\&. 
.PP
.RE
.PP

.SS "uint16_t EE_WriteVariable (uint16_t VirtAddress, uint16_t Data)"

.PP
Writes/upadtes variable data in EEPROM\&. 
.PP
\fBParameters:\fP
.RS 4
\fIVirtAddress\fP Variable virtual address 
.br
\fIData\fP 16 bit data to be written 
.RE
.PP
\fBReturn values:\fP
.RS 4
\fISuccess\fP or error status:
.IP "\(bu" 2
FLASH_COMPLETE: on success
.IP "\(bu" 2
PAGE_FULL: if valid page is full
.IP "\(bu" 2
NO_VALID_PAGE: if no valid page was found
.IP "\(bu" 2
Flash error code: on write Flash error 
.PP
.RE
.PP

.SH "Variable Documentation"
.PP 
.SS "uint16_t DataVar = 0"

.SS "uint16_t VirtAddVarTab[\fBNB_OF_VAR\fP]"

.SH "Author"
.PP 
Generated automatically by Doxygen from the source code\&.
