.TH "eeprom.c" 3 "Wed Sep 16 2015" "Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
eeprom.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'eeprom\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "uint16_t \fBEE_Init\fP (void)"
.br
.RI "\fIRestore the pages to a known good state in case of page's status corruption after a power loss\&. \fP"
.ti -1c
.RI "uint16_t \fBEE_ReadVariable\fP (uint16_t VirtAddress, uint16_t *Data)"
.br
.RI "\fIReturns the last stored variable data, if found, which correspond to the passed virtual address\&. \fP"
.ti -1c
.RI "uint16_t \fBEE_WriteVariable\fP (uint16_t VirtAddress, uint16_t Data)"
.br
.RI "\fIWrites/upadtes variable data in EEPROM\&. \fP"
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "uint16_t \fBDataVar\fP = 0"
.br
.ti -1c
.RI "uint16_t \fBVirtAddVarTab\fP [\fBNB_OF_VAR\fP]"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen from the source code\&.
