.TH "encoder.h" 3 "Wed Sep 16 2015" "Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
encoder.h \- 
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBencoder_init\fP (void)"
.br
.ti -1c
.RI "float \fBencoder_read_deg\fP (void)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void encoder_init (void)"

.SS "float encoder_read_deg (void)"

.SH "Author"
.PP 
Generated automatically by Doxygen from the source code\&.
