.TH "fault_data" 3 "Wed Sep 16 2015" "Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
fault_data \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <datatypes\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBmc_fault_code\fP \fBfault\fP"
.br
.ti -1c
.RI "float \fBcurrent\fP"
.br
.ti -1c
.RI "float \fBcurrent_filtered\fP"
.br
.ti -1c
.RI "float \fBvoltage\fP"
.br
.ti -1c
.RI "float \fBduty\fP"
.br
.ti -1c
.RI "float \fBrpm\fP"
.br
.ti -1c
.RI "int \fBtacho\fP"
.br
.ti -1c
.RI "int \fBcycles_running\fP"
.br
.ti -1c
.RI "int \fBpwm_cycles\fP"
.br
.ti -1c
.RI "int \fBtim_val_samp\fP"
.br
.ti -1c
.RI "int \fBtim_current_samp\fP"
.br
.ti -1c
.RI "int \fBtim_top\fP"
.br
.ti -1c
.RI "int \fBcomm_step\fP"
.br
.ti -1c
.RI "float \fBtemperature\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "int comm_step"

.SS "float current"

.SS "float current_filtered"

.SS "int cycles_running"

.SS "float duty"

.SS "\fBmc_fault_code\fP fault"

.SS "int pwm_cycles"

.SS "float rpm"

.SS "int tacho"

.SS "float temperature"

.SS "int tim_current_samp"

.SS "int tim_top"

.SS "int tim_val_samp"

.SS "float voltage"


.SH "Author"
.PP 
Generated automatically by Doxygen from the source code\&.
