.TH "flash_helper.h" 3 "Wed Sep 16 2015" "Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
flash_helper.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'conf_general\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "uint16_t \fBflash_helper_erase_new_app\fP (uint32_t new_app_size)"
.br
.ti -1c
.RI "uint16_t \fBflash_helper_write_new_app_data\fP (uint32_t offset, uint8_t *data, uint32_t len)"
.br
.ti -1c
.RI "void \fBflash_helper_jump_to_bootloader\fP (void)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "uint16_t flash_helper_erase_new_app (uint32_t new_app_size)"

.SS "void flash_helper_jump_to_bootloader (void)"
Stop the system and jump to the bootloader\&. 
.SS "uint16_t flash_helper_write_new_app_data (uint32_t offset, uint8_t * data, uint32_t len)"

.SH "Author"
.PP 
Generated automatically by Doxygen from the source code\&.
