.TH "hwconf/hw.h" 3 "Wed Sep 16 2015" "Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
hwconf/hw.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'conf_general\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBhw_init_gpio\fP (void)"
.br
.ti -1c
.RI "void \fBhw_setup_adc_channels\fP (void)"
.br
.ti -1c
.RI "void \fBhw_setup_servo_outputs\fP (void)"
.br
.ti -1c
.RI "void \fBhw_start_i2c\fP (void)"
.br
.ti -1c
.RI "void \fBhw_stop_i2c\fP (void)"
.br
.ti -1c
.RI "void \fBhw_try_restore_i2c\fP (void)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void hw_init_gpio (void)"

.SS "void hw_setup_adc_channels (void)"

.SS "void hw_setup_servo_outputs (void)"

.SS "void hw_start_i2c (void)"

.SS "void hw_stop_i2c (void)"

.SS "void hw_try_restore_i2c (void)"

.SH "Author"
.PP 
Generated automatically by Doxygen from the source code\&.
