.TH "irq_handlers.c" 3 "Wed Sep 16 2015" "Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
irq_handlers.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'ch\&.h'\fP
.br
\fC#include 'hal\&.h'\fP
.br
\fC#include <stm32f4xx\&.h>\fP
.br
\fC#include 'stm32f4xx_conf\&.h'\fP
.br
\fC#include 'main\&.h'\fP
.br
\fC#include 'mcpwm\&.h'\fP
.br
\fC#include 'servo\&.h'\fP
.br
\fC#include 'hw\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBCH_IRQ_HANDLER\fP (ADC1_2_3_IRQHandler)"
.br
.ti -1c
.RI "\fBCH_IRQ_HANDLER\fP (\fBHW_ENC_EXTI_ISR_VEC\fP)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "CH_IRQ_HANDLER (ADC1_2_3_IRQHandler)"

.SS "CH_IRQ_HANDLER (\fBHW_ENC_EXTI_ISR_VEC\fP)"

.SH "Author"
.PP 
Generated automatically by Doxygen from the source code\&.
