.TH "led_external.c" 3 "Wed Sep 16 2015" "Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
led_external.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'led_external\&.h'\fP
.br
\fC#include 'ch\&.h'\fP
.br
\fC#include 'hal\&.h'\fP
.br
\fC#include 'ws2811\&.h'\fP
.br
\fC#include 'mcpwm\&.h'\fP
.br
\fC#include 'utils\&.h'\fP
.br
\fC#include 'hw\&.h'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBHAS_FAULT\fP()   (\fBmcpwm_get_fault\fP() != \fBFAULT_CODE_NONE\fP)"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBled_external_init\fP (void)"
.br
.ti -1c
.RI "void \fBled_external_set_state\fP (\fBLED_EXT_STATE\fP new_state)"
.br
.ti -1c
.RI "void \fBled_external_set_reversed\fP (bool newstate)"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define HAS_FAULT()   (\fBmcpwm_get_fault\fP() != \fBFAULT_CODE_NONE\fP)"

.SH "Function Documentation"
.PP 
.SS "void led_external_init (void)"

.SS "void led_external_set_reversed (bool newstate)"

.SS "void led_external_set_state (\fBLED_EXT_STATE\fP new_state)"

.SH "Author"
.PP 
Generated automatically by Doxygen from the source code\&.
