.TH "led_external.h" 3 "Wed Sep 16 2015" "Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
led_external.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'datatypes\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBled_external_init\fP (void)"
.br
.ti -1c
.RI "void \fBled_external_set_state\fP (\fBLED_EXT_STATE\fP new_state)"
.br
.ti -1c
.RI "void \fBled_external_set_reversed\fP (bool newstate)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void led_external_init (void)"

.SS "void led_external_set_reversed (bool newstate)"

.SS "void led_external_set_state (\fBLED_EXT_STATE\fP new_state)"

.SH "Author"
.PP 
Generated automatically by Doxygen from the source code\&.
