.TH "ledpwm.c" 3 "Wed Sep 16 2015" "Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ledpwm.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'ledpwm\&.h'\fP
.br
\fC#include 'ch\&.h'\fP
.br
\fC#include 'hal\&.h'\fP
.br
\fC#include <string\&.h>\fP
.br
\fC#include <math\&.h>\fP
.br
\fC#include 'hw\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBledpwm_init\fP (void)"
.br
.ti -1c
.RI "void \fBledpwm_set_intensity\fP (unsigned int led, float intensity)"
.br
.ti -1c
.RI "void \fBledpwm_led_on\fP (int led)"
.br
.ti -1c
.RI "void \fBledpwm_led_off\fP (int led)"
.br
.ti -1c
.RI "void \fBledpwm_update_pwm\fP (void)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void ledpwm_init (void)"

.SS "void ledpwm_led_off (int led)"

.SS "void ledpwm_led_on (int led)"

.SS "void ledpwm_set_intensity (unsigned int led, float intensity)"

.SS "void ledpwm_update_pwm (void)"

.SH "Author"
.PP 
Generated automatically by Doxygen from the source code\&.
