.TH "ledpwm.h" 3 "Wed Sep 16 2015" "Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ledpwm.h \- 
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBLEDPWM_LED_NUM\fP   2"
.br
.ti -1c
.RI "#define \fBLEDPWM_CNT_TOP\fP   200"
.br
.ti -1c
.RI "#define \fBLED_GREEN\fP   0"
.br
.ti -1c
.RI "#define \fBLED_RED\fP   1"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBledpwm_init\fP (void)"
.br
.ti -1c
.RI "void \fBledpwm_set_intensity\fP (unsigned int led, float intensity)"
.br
.ti -1c
.RI "void \fBledpwm_led_on\fP (int led)"
.br
.ti -1c
.RI "void \fBledpwm_led_off\fP (int led)"
.br
.ti -1c
.RI "void \fBledpwm_update_pwm\fP (void)"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define LED_GREEN   0"

.SS "#define LED_RED   1"

.SS "#define LEDPWM_CNT_TOP   200"

.SS "#define LEDPWM_LED_NUM   2"

.SH "Function Documentation"
.PP 
.SS "void ledpwm_init (void)"

.SS "void ledpwm_led_off (int led)"

.SS "void ledpwm_led_on (int led)"

.SS "void ledpwm_set_intensity (unsigned int led, float intensity)"

.SS "void ledpwm_update_pwm (void)"

.SH "Author"
.PP 
Generated automatically by Doxygen from the source code\&.
