.TH "main.c" 3 "Wed Sep 16 2015" "Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
main.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'ch\&.h'\fP
.br
\fC#include 'hal\&.h'\fP
.br
\fC#include 'stm32f4xx_conf\&.h'\fP
.br
\fC#include <stdio\&.h>\fP
.br
\fC#include <math\&.h>\fP
.br
\fC#include <string\&.h>\fP
.br
\fC#include <stdlib\&.h>\fP
.br
\fC#include 'main\&.h'\fP
.br
\fC#include 'mcpwm\&.h'\fP
.br
\fC#include 'ledpwm\&.h'\fP
.br
\fC#include 'comm_usb\&.h'\fP
.br
\fC#include 'terminal\&.h'\fP
.br
\fC#include 'hw\&.h'\fP
.br
\fC#include 'app\&.h'\fP
.br
\fC#include 'packet\&.h'\fP
.br
\fC#include 'commands\&.h'\fP
.br
\fC#include 'timeout\&.h'\fP
.br
\fC#include 'comm_can\&.h'\fP
.br
\fC#include 'ws2811\&.h'\fP
.br
\fC#include 'led_external\&.h'\fP
.br
\fC#include 'encoder\&.h'\fP
.br
\fC#include 'servo\&.h'\fP
.br
\fC#include 'servo_simple\&.h'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBADC_SAMPLE_MAX_LEN\fP   2000"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBmain_dma_adc_handler\fP (void)"
.br
.ti -1c
.RI "float \fBmain_get_last_adc_isr_duration\fP (void)"
.br
.ti -1c
.RI "void \fBmain_sample_print_data\fP (bool at_start, uint16_t len, uint8_t decimation)"
.br
.ti -1c
.RI "int \fBmain\fP (void)"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define ADC_SAMPLE_MAX_LEN   2000"

.SH "Function Documentation"
.PP 
.SS "int main (void)"

.SS "void main_dma_adc_handler (void)"

.SS "float main_get_last_adc_isr_duration (void)"

.SS "void main_sample_print_data (bool at_start, uint16_t len, uint8_t decimation)"

.SH "Author"
.PP 
Generated automatically by Doxygen from the source code\&.
