.TH "main.h" 3 "Wed Sep 16 2015" "Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
main.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <stdint\&.h>\fP
.br
\fC#include 'conf_general\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBmain_dma_adc_handler\fP (void)"
.br
.ti -1c
.RI "float \fBmain_get_last_adc_isr_duration\fP (void)"
.br
.ti -1c
.RI "void \fBmain_sample_print_data\fP (bool at_start, uint16_t len, uint8_t decimation)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void main_dma_adc_handler (void)"

.SS "float main_get_last_adc_isr_duration (void)"

.SS "void main_sample_print_data (bool at_start, uint16_t len, uint8_t decimation)"

.SH "Author"
.PP 
Generated automatically by Doxygen from the source code\&.
