.TH "mc_configuration" 3 "Wed Sep 16 2015" "Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
mc_configuration \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <datatypes\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBmc_pwm_mode\fP \fBpwm_mode\fP"
.br
.ti -1c
.RI "\fBmc_comm_mode\fP \fBcomm_mode\fP"
.br
.ti -1c
.RI "\fBmc_motor_type\fP \fBmotor_type\fP"
.br
.ti -1c
.RI "\fBmc_sensor_mode\fP \fBsensor_mode\fP"
.br
.ti -1c
.RI "float \fBl_current_max\fP"
.br
.ti -1c
.RI "float \fBl_current_min\fP"
.br
.ti -1c
.RI "float \fBl_in_current_max\fP"
.br
.ti -1c
.RI "float \fBl_in_current_min\fP"
.br
.ti -1c
.RI "float \fBl_abs_current_max\fP"
.br
.ti -1c
.RI "float \fBl_min_erpm\fP"
.br
.ti -1c
.RI "float \fBl_max_erpm\fP"
.br
.ti -1c
.RI "float \fBl_max_erpm_fbrake\fP"
.br
.ti -1c
.RI "float \fBl_max_erpm_fbrake_cc\fP"
.br
.ti -1c
.RI "float \fBl_min_vin\fP"
.br
.ti -1c
.RI "float \fBl_max_vin\fP"
.br
.ti -1c
.RI "float \fBl_battery_cut_start\fP"
.br
.ti -1c
.RI "float \fBl_battery_cut_end\fP"
.br
.ti -1c
.RI "bool \fBl_slow_abs_current\fP"
.br
.ti -1c
.RI "bool \fBl_rpm_lim_neg_torque\fP"
.br
.ti -1c
.RI "float \fBl_temp_fet_start\fP"
.br
.ti -1c
.RI "float \fBl_temp_fet_end\fP"
.br
.ti -1c
.RI "float \fBl_temp_motor_start\fP"
.br
.ti -1c
.RI "float \fBl_temp_motor_end\fP"
.br
.ti -1c
.RI "float \fBl_min_duty\fP"
.br
.ti -1c
.RI "float \fBl_max_duty\fP"
.br
.ti -1c
.RI "float \fBlo_current_max\fP"
.br
.ti -1c
.RI "float \fBlo_current_min\fP"
.br
.ti -1c
.RI "float \fBlo_in_current_max\fP"
.br
.ti -1c
.RI "float \fBlo_in_current_min\fP"
.br
.ti -1c
.RI "float \fBsl_min_erpm\fP"
.br
.ti -1c
.RI "float \fBsl_min_erpm_cycle_int_limit\fP"
.br
.ti -1c
.RI "float \fBsl_max_fullbreak_current_dir_change\fP"
.br
.ti -1c
.RI "float \fBsl_cycle_int_limit\fP"
.br
.ti -1c
.RI "float \fBsl_phase_advance_at_br\fP"
.br
.ti -1c
.RI "float \fBsl_cycle_int_rpm_br\fP"
.br
.ti -1c
.RI "float \fBsl_bemf_coupling_k\fP"
.br
.ti -1c
.RI "int8_t \fBhall_table\fP [8]"
.br
.ti -1c
.RI "float \fBhall_sl_erpm\fP"
.br
.ti -1c
.RI "float \fBs_pid_kp\fP"
.br
.ti -1c
.RI "float \fBs_pid_ki\fP"
.br
.ti -1c
.RI "float \fBs_pid_kd\fP"
.br
.ti -1c
.RI "float \fBs_pid_min_rpm\fP"
.br
.ti -1c
.RI "float \fBp_pid_kp\fP"
.br
.ti -1c
.RI "float \fBp_pid_ki\fP"
.br
.ti -1c
.RI "float \fBp_pid_kd\fP"
.br
.ti -1c
.RI "float \fBcc_startup_boost_duty\fP"
.br
.ti -1c
.RI "float \fBcc_min_current\fP"
.br
.ti -1c
.RI "float \fBcc_gain\fP"
.br
.ti -1c
.RI "float \fBcc_ramp_step_max\fP"
.br
.ti -1c
.RI "int32_t \fBm_fault_stop_time_ms\fP"
.br
.ti -1c
.RI "float \fBm_duty_ramp_step\fP"
.br
.ti -1c
.RI "float \fBm_duty_ramp_step_rpm_lim\fP"
.br
.ti -1c
.RI "float \fBm_current_backoff_gain\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "float cc_gain"

.SS "float cc_min_current"

.SS "float cc_ramp_step_max"

.SS "float cc_startup_boost_duty"

.SS "\fBmc_comm_mode\fP comm_mode"

.SS "float hall_sl_erpm"

.SS "int8_t hall_table[8]"

.SS "float l_abs_current_max"

.SS "float l_battery_cut_end"

.SS "float l_battery_cut_start"

.SS "float l_current_max"

.SS "float l_current_min"

.SS "float l_in_current_max"

.SS "float l_in_current_min"

.SS "float l_max_duty"

.SS "float l_max_erpm"

.SS "float l_max_erpm_fbrake"

.SS "float l_max_erpm_fbrake_cc"

.SS "float l_max_vin"

.SS "float l_min_duty"

.SS "float l_min_erpm"

.SS "float l_min_vin"

.SS "bool l_rpm_lim_neg_torque"

.SS "bool l_slow_abs_current"

.SS "float l_temp_fet_end"

.SS "float l_temp_fet_start"

.SS "float l_temp_motor_end"

.SS "float l_temp_motor_start"

.SS "float lo_current_max"

.SS "float lo_current_min"

.SS "float lo_in_current_max"

.SS "float lo_in_current_min"

.SS "float m_current_backoff_gain"

.SS "float m_duty_ramp_step"

.SS "float m_duty_ramp_step_rpm_lim"

.SS "int32_t m_fault_stop_time_ms"

.SS "\fBmc_motor_type\fP motor_type"

.SS "float p_pid_kd"

.SS "float p_pid_ki"

.SS "float p_pid_kp"

.SS "\fBmc_pwm_mode\fP pwm_mode"

.SS "float s_pid_kd"

.SS "float s_pid_ki"

.SS "float s_pid_kp"

.SS "float s_pid_min_rpm"

.SS "\fBmc_sensor_mode\fP sensor_mode"

.SS "float sl_bemf_coupling_k"

.SS "float sl_cycle_int_limit"

.SS "float sl_cycle_int_rpm_br"

.SS "float sl_max_fullbreak_current_dir_change"

.SS "float sl_min_erpm"

.SS "float sl_min_erpm_cycle_int_limit"

.SS "float sl_phase_advance_at_br"


.SH "Author"
.PP 
Generated automatically by Doxygen from the source code\&.
