.TH "mc_rpm_dep_struct" 3 "Wed Sep 16 2015" "Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
mc_rpm_dep_struct \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <datatypes\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "float \fBcycle_int_limit\fP"
.br
.ti -1c
.RI "float \fBcycle_int_limit_running\fP"
.br
.ti -1c
.RI "float \fBcycle_int_limit_max\fP"
.br
.ti -1c
.RI "float \fBcomm_time_sum\fP"
.br
.ti -1c
.RI "float \fBcomm_time_sum_min_rpm\fP"
.br
.ti -1c
.RI "int32_t \fBcomms\fP"
.br
.ti -1c
.RI "uint32_t \fBtime_at_comm\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "float comm_time_sum"

.SS "float comm_time_sum_min_rpm"

.SS "int32_t comms"

.SS "float cycle_int_limit"

.SS "float cycle_int_limit_max"

.SS "float cycle_int_limit_running"

.SS "uint32_t time_at_comm"


.SH "Author"
.PP 
Generated automatically by Doxygen from the source code\&.
