.TH "mc_timer_struct" 3 "Wed Sep 16 2015" "Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
mc_timer_struct \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "volatile bool \fBupdated\fP"
.br
.ti -1c
.RI "volatile unsigned int \fBtop\fP"
.br
.ti -1c
.RI "volatile unsigned int \fBduty\fP"
.br
.ti -1c
.RI "volatile unsigned int \fBval_sample\fP"
.br
.ti -1c
.RI "volatile unsigned int \fBcurr1_sample\fP"
.br
.ti -1c
.RI "volatile unsigned int \fBcurr2_sample\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "volatile unsigned int curr1_sample"

.SS "volatile unsigned int curr2_sample"

.SS "volatile unsigned int duty"

.SS "volatile unsigned int top"

.SS "volatile bool updated"

.SS "volatile unsigned int val_sample"


.SH "Author"
.PP 
Generated automatically by Doxygen from the source code\&.
