.TH "mcconf/mcconf_outrunner2.h" 3 "Wed Sep 16 2015" "Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
mcconf/mcconf_outrunner2.h \- 
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBMCPWM_CURRENT_MAX\fP   60\&.0"
.br
.ti -1c
.RI "#define \fBMCPWM_CURRENT_MIN\fP   \-60\&.0"
.br
.ti -1c
.RI "#define \fBMCPWM_IN_CURRENT_MAX\fP   60\&.0"
.br
.ti -1c
.RI "#define \fBMCPWM_IN_CURRENT_MIN\fP   \-20\&.0"
.br
.ti -1c
.RI "#define \fBMCPWM_MAX_ABS_CURRENT\fP   130\&.0"
.br
.ti -1c
.RI "#define \fBMCPWM_SLOW_ABS_OVERCURRENT\fP   1"
.br
.ti -1c
.RI "#define \fBMCPWM_SENSOR_MODE\fP   \fBSENSOR_MODE_SENSORLESS\fP"
.br
.ti -1c
.RI "#define \fBMCPWM_MIN_RPM\fP   150"
.br
.ti -1c
.RI "#define \fBMCPWM_CYCLE_INT_LIMIT_MIN_RPM\fP   1100\&.0"
.br
.ti -1c
.RI "#define \fBMCPWM_CYCLE_INT_LIMIT\fP   62\&.0"
.br
.ti -1c
.RI "#define \fBMCPWM_CYCLE_INT_LIMIT_HIGH_FAC\fP   0\&.8"
.br
.ti -1c
.RI "#define \fBMCPWM_BEMF_INPUT_COUPLING_K\fP   600\&.0"
.br
.ti -1c
.RI "#define \fBMCPWM_PID_KP\fP   0\&.0001"
.br
.ti -1c
.RI "#define \fBMCPWM_PID_KI\fP   0\&.002"
.br
.ti -1c
.RI "#define \fBMCPWM_PID_KD\fP   0\&.0"
.br
.ti -1c
.RI "#define \fBMCPWM_PID_MIN_RPM\fP   900\&.0"
.br
.ti -1c
.RI "#define \fBMCPWM_P_PID_KP\fP   0\&.0001"
.br
.ti -1c
.RI "#define \fBMCPWM_P_PID_KI\fP   0\&.002"
.br
.ti -1c
.RI "#define \fBMCPWM_P_PID_KD\fP   0\&.0"
.br
.ti -1c
.RI "#define \fBMCPWM_CURRENT_CONTROL_GAIN\fP   0\&.0046"
.br
.ti -1c
.RI "#define \fBMCPWM_CURRENT_CONTROL_MIN\fP   1\&.0"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define MCPWM_BEMF_INPUT_COUPLING_K   600\&.0"

.SS "#define MCPWM_CURRENT_CONTROL_GAIN   0\&.0046"

.SS "#define MCPWM_CURRENT_CONTROL_MIN   1\&.0"

.SS "#define MCPWM_CURRENT_MAX   60\&.0"

.SS "#define MCPWM_CURRENT_MIN   \-60\&.0"

.SS "#define MCPWM_CYCLE_INT_LIMIT   62\&.0"

.SS "#define MCPWM_CYCLE_INT_LIMIT_HIGH_FAC   0\&.8"

.SS "#define MCPWM_CYCLE_INT_LIMIT_MIN_RPM   1100\&.0"

.SS "#define MCPWM_IN_CURRENT_MAX   60\&.0"

.SS "#define MCPWM_IN_CURRENT_MIN   \-20\&.0"

.SS "#define MCPWM_MAX_ABS_CURRENT   130\&.0"

.SS "#define MCPWM_MIN_RPM   150"

.SS "#define MCPWM_P_PID_KD   0\&.0"

.SS "#define MCPWM_P_PID_KI   0\&.002"

.SS "#define MCPWM_P_PID_KP   0\&.0001"

.SS "#define MCPWM_PID_KD   0\&.0"

.SS "#define MCPWM_PID_KI   0\&.002"

.SS "#define MCPWM_PID_KP   0\&.0001"

.SS "#define MCPWM_PID_MIN_RPM   900\&.0"

.SS "#define MCPWM_SENSOR_MODE   \fBSENSOR_MODE_SENSORLESS\fP"

.SS "#define MCPWM_SLOW_ABS_OVERCURRENT   1"

.SH "Author"
.PP 
Generated automatically by Doxygen from the source code\&.
