.TH "mcconf/mcconf_sten.h" 3 "Wed Sep 16 2015" "Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
mcconf/mcconf_sten.h \- 
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBMCPWM_CURRENT_MAX\fP   35\&.0"
.br
.ti -1c
.RI "#define \fBMCPWM_CURRENT_MIN\fP   \-30\&.0"
.br
.ti -1c
.RI "#define \fBMCPWM_MAX_ABS_CURRENT\fP   100\&.0"
.br
.ti -1c
.RI "#define \fBMCPWM_SLOW_ABS_OVERCURRENT\fP   1"
.br
.ti -1c
.RI "#define \fBMCPWM_IN_CURRENT_MAX\fP   25\&.0"
.br
.ti -1c
.RI "#define \fBMCPWM_IN_CURRENT_MIN\fP   \-20\&.0"
.br
.ti -1c
.RI "#define \fBMCPWM_RPM_MAX\fP   80000\&.0"
.br
.ti -1c
.RI "#define \fBMCPWM_RPM_MIN\fP   \-80000\&.0"
.br
.ti -1c
.RI "#define \fBMCPWM_MIN_VOLTAGE\fP   20\&.0"
.br
.ti -1c
.RI "#define \fBMCPWM_MAX_VOLTAGE\fP   50\&.0"
.br
.ti -1c
.RI "#define \fBMCPWM_CURRENT_STARTUP_BOOST\fP   0\&.02"
.br
.ti -1c
.RI "#define \fBMCPWM_RPM_LIMIT_NEG_TORQUE\fP   0"
.br
.ti -1c
.RI "#define \fBMCPWM_CURR_MAX_RPM_FBRAKE\fP   1500"
.br
.ti -1c
.RI "#define \fBMCPWM_SENSOR_MODE\fP   \fBSENSOR_MODE_SENSORLESS\fP"
.br
.ti -1c
.RI "#define \fBMCPWM_MIN_RPM\fP   250"
.br
.ti -1c
.RI "#define \fBMCPWM_CYCLE_INT_LIMIT_MIN_RPM\fP   500\&.0"
.br
.ti -1c
.RI "#define \fBMCPWM_CYCLE_INT_LIMIT\fP   80\&.0"
.br
.ti -1c
.RI "#define \fBMCPWM_CYCLE_INT_LIMIT_HIGH_FAC\fP   0\&.8"
.br
.ti -1c
.RI "#define \fBMCPWM_BEMF_INPUT_COUPLING_K\fP   750\&.0"
.br
.ti -1c
.RI "#define \fBMCPWM_PID_KP\fP   0\&.0001"
.br
.ti -1c
.RI "#define \fBMCPWM_PID_KI\fP   0\&.002"
.br
.ti -1c
.RI "#define \fBMCPWM_PID_KD\fP   0\&.0"
.br
.ti -1c
.RI "#define \fBMCPWM_PID_MIN_RPM\fP   1200\&.0"
.br
.ti -1c
.RI "#define \fBMCPWM_P_PID_KP\fP   0\&.0001"
.br
.ti -1c
.RI "#define \fBMCPWM_P_PID_KI\fP   0\&.002"
.br
.ti -1c
.RI "#define \fBMCPWM_P_PID_KD\fP   0\&.0"
.br
.ti -1c
.RI "#define \fBMCPWM_CURRENT_CONTROL_GAIN\fP   0\&.0046"
.br
.ti -1c
.RI "#define \fBMCPWM_CURRENT_CONTROL_MIN\fP   0\&.05"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define MCPWM_BEMF_INPUT_COUPLING_K   750\&.0"

.SS "#define MCPWM_CURR_MAX_RPM_FBRAKE   1500"

.SS "#define MCPWM_CURRENT_CONTROL_GAIN   0\&.0046"

.SS "#define MCPWM_CURRENT_CONTROL_MIN   0\&.05"

.SS "#define MCPWM_CURRENT_MAX   35\&.0"

.SS "#define MCPWM_CURRENT_MIN   \-30\&.0"

.SS "#define MCPWM_CURRENT_STARTUP_BOOST   0\&.02"

.SS "#define MCPWM_CYCLE_INT_LIMIT   80\&.0"

.SS "#define MCPWM_CYCLE_INT_LIMIT_HIGH_FAC   0\&.8"

.SS "#define MCPWM_CYCLE_INT_LIMIT_MIN_RPM   500\&.0"

.SS "#define MCPWM_IN_CURRENT_MAX   25\&.0"

.SS "#define MCPWM_IN_CURRENT_MIN   \-20\&.0"

.SS "#define MCPWM_MAX_ABS_CURRENT   100\&.0"

.SS "#define MCPWM_MAX_VOLTAGE   50\&.0"

.SS "#define MCPWM_MIN_RPM   250"

.SS "#define MCPWM_MIN_VOLTAGE   20\&.0"

.SS "#define MCPWM_P_PID_KD   0\&.0"

.SS "#define MCPWM_P_PID_KI   0\&.002"

.SS "#define MCPWM_P_PID_KP   0\&.0001"

.SS "#define MCPWM_PID_KD   0\&.0"

.SS "#define MCPWM_PID_KI   0\&.002"

.SS "#define MCPWM_PID_KP   0\&.0001"

.SS "#define MCPWM_PID_MIN_RPM   1200\&.0"

.SS "#define MCPWM_RPM_LIMIT_NEG_TORQUE   0"

.SS "#define MCPWM_RPM_MAX   80000\&.0"

.SS "#define MCPWM_RPM_MIN   \-80000\&.0"

.SS "#define MCPWM_SENSOR_MODE   \fBSENSOR_MODE_SENSORLESS\fP"

.SS "#define MCPWM_SLOW_ABS_OVERCURRENT   1"

.SH "Author"
.PP 
Generated automatically by Doxygen from the source code\&.
