.TH "mote_state" 3 "Wed Sep 16 2015" "Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
mote_state \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <datatypes\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "uint8_t \fBjs_x\fP"
.br
.ti -1c
.RI "uint8_t \fBjs_y\fP"
.br
.ti -1c
.RI "bool \fBbt_c\fP"
.br
.ti -1c
.RI "bool \fBbt_z\fP"
.br
.ti -1c
.RI "bool \fBbt_push\fP"
.br
.ti -1c
.RI "float \fBvbat\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "bool bt_c"

.SS "bool bt_push"

.SS "bool bt_z"

.SS "uint8_t js_x"

.SS "uint8_t js_y"

.SS "float vbat"


.SH "Author"
.PP 
Generated automatically by Doxygen from the source code\&.
