.TH "myUSB.h" 3 "Wed Sep 16 2015" "Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
myUSB.h \- 
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBmyUSBinit\fP (void)"
.br
.ti -1c
.RI "int \fBisUsbActive\fP (void)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "SerialUSBDriver \fBSDU1\fP"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int isUsbActive (void)"

.SS "void myUSBinit (void)"

.SH "Variable Documentation"
.PP 
.SS "SerialUSBDriver SDU1"

.SH "Author"
.PP 
Generated automatically by Doxygen from the source code\&.
