.TH "myUSB.c" 3 "Wed Sep 16 2015" "Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
myUSB.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'ch\&.h'\fP
.br
\fC#include 'hal\&.h'\fP
.br
\fC#include 'myUSB\&.h'\fP
.br
\fC#include 'usbdescriptor\&.h'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBUSBD1_DATA_REQUEST_EP\fP   1"
.br
.ti -1c
.RI "#define \fBUSBD1_DATA_AVAILABLE_EP\fP   1"
.br
.ti -1c
.RI "#define \fBUSBD1_INTERRUPT_REQUEST_EP\fP   2"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBisUsbActive\fP (void)"
.br
.ti -1c
.RI "void \fBmyUSBinit\fP (void)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "SerialUSBDriver \fBSDU1\fP"
.br
.ti -1c
.RI "const USBConfig \fBusbcfg\fP"
.br
.ti -1c
.RI "const SerialUSBConfig \fBserusbcfg\fP"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define USBD1_DATA_AVAILABLE_EP   1"

.SS "#define USBD1_DATA_REQUEST_EP   1"

.SS "#define USBD1_INTERRUPT_REQUEST_EP   2"

.SH "Function Documentation"
.PP 
.SS "int isUsbActive (void)"

.SS "void myUSBinit (void)"

.SH "Variable Documentation"
.PP 
.SS "SerialUSBDriver SDU1"

.SS "const SerialUSBConfig serusbcfg"
\fBInitial value:\fP
.PP
.nf
= {
        &USBD1,
        USBD1_DATA_REQUEST_EP,
        USBD1_DATA_AVAILABLE_EP,
        USBD1_INTERRUPT_REQUEST_EP
}
.fi
.SS "const USBConfig usbcfg"
\fBInitial value:\fP
.PP
.nf
= {
        usb_event,
        get_descriptor,
        sduRequestsHook,
        NULL
}
.fi
.SH "Author"
.PP 
Generated automatically by Doxygen from the source code\&.
