.TH "nrf/nrf_driver.c" 3 "Wed Sep 16 2015" "Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
nrf/nrf_driver.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'nrf_driver\&.h'\fP
.br
\fC#include 'rf\&.h'\fP
.br
\fC#include 'rfhelp\&.h'\fP
.br
\fC#include 'conf_general\&.h'\fP
.br
\fC#include 'app\&.h'\fP
.br
\fC#include 'buffer\&.h'\fP
.br
\fC#include 'commands\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBnrf_driver_init\fP (void)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void nrf_driver_init (void)"

.SH "Author"
.PP 
Generated automatically by Doxygen from the source code\&.
