.TH "packet.c" 3 "Wed Sep 16 2015" "Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
packet.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <string\&.h>\fP
.br
\fC#include 'packet\&.h'\fP
.br
\fC#include 'crc\&.h'\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBPACKET_STATE_t\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBpacket_init\fP (void(*s_func)(unsigned char *data, unsigned int len), void(*p_func)(unsigned char *data, unsigned int len), int handler_num)"
.br
.ti -1c
.RI "void \fBpacket_send_packet\fP (unsigned char *data, unsigned int len, int handler_num)"
.br
.ti -1c
.RI "void \fBpacket_timerfunc\fP (void)"
.br
.ti -1c
.RI "void \fBpacket_process_byte\fP (uint8_t rx_data, int handler_num)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void packet_init (void(*)(unsigned char *data, unsigned int len) s_func, void(*)(unsigned char *data, unsigned int len) p_func, int handler_num)"

.SS "void packet_process_byte (uint8_t rx_data, int handler_num)"

.SS "void packet_send_packet (unsigned char * data, unsigned int len, int handler_num)"

.SS "void packet_timerfunc (void)"
Call this function every millisecond\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen from the source code\&.
