.TH "packet.h" 3 "Wed Sep 16 2015" "Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
packet.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <stdint\&.h>\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBPACKET_RX_TIMEOUT\fP   2"
.br
.ti -1c
.RI "#define \fBPACKET_HANDLERS\fP   2"
.br
.ti -1c
.RI "#define \fBPACKET_MAX_PL_LEN\fP   1024"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBpacket_init\fP (void(*s_func)(unsigned char *data, unsigned int len), void(*p_func)(unsigned char *data, unsigned int len), int handler_num)"
.br
.ti -1c
.RI "void \fBpacket_process_byte\fP (uint8_t rx_data, int handler_num)"
.br
.ti -1c
.RI "void \fBpacket_timerfunc\fP (void)"
.br
.ti -1c
.RI "void \fBpacket_send_packet\fP (unsigned char *data, unsigned int len, int handler_num)"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define PACKET_HANDLERS   2"

.SS "#define PACKET_MAX_PL_LEN   1024"

.SS "#define PACKET_RX_TIMEOUT   2"

.SH "Function Documentation"
.PP 
.SS "void packet_init (void(*)(unsigned char *data, unsigned int len) s_func, void(*)(unsigned char *data, unsigned int len) p_func, int handler_num)"

.SS "void packet_process_byte (uint8_t rx_data, int handler_num)"

.SS "void packet_send_packet (unsigned char * data, unsigned int len, int handler_num)"

.SS "void packet_timerfunc (void)"
Call this function every millisecond\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen from the source code\&.
