.TH "PACKET_STATE_t" 3 "Wed Sep 16 2015" "Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PACKET_STATE_t \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "volatile unsigned char \fBrx_state\fP"
.br
.ti -1c
.RI "volatile unsigned char \fBrx_timeout\fP"
.br
.ti -1c
.RI "void(* \fBsend_func\fP )(unsigned char *data, unsigned int len)"
.br
.ti -1c
.RI "void(* \fBprocess_func\fP )(unsigned char *data, unsigned int len)"
.br
.ti -1c
.RI "unsigned int \fBpayload_length\fP"
.br
.ti -1c
.RI "unsigned char \fBrx_buffer\fP [\fBPACKET_MAX_PL_LEN\fP]"
.br
.ti -1c
.RI "unsigned char \fBtx_buffer\fP [\fBPACKET_MAX_PL_LEN\fP+6]"
.br
.ti -1c
.RI "unsigned int \fBrx_data_ptr\fP"
.br
.ti -1c
.RI "unsigned char \fBcrc_low\fP"
.br
.ti -1c
.RI "unsigned char \fBcrc_high\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "unsigned char crc_high"

.SS "unsigned char crc_low"

.SS "unsigned int payload_length"

.SS "void(* process_func) (unsigned char *data, unsigned int len)"

.SS "unsigned char rx_buffer[\fBPACKET_MAX_PL_LEN\fP]"

.SS "unsigned int rx_data_ptr"

.SS "volatile unsigned char rx_state"

.SS "volatile unsigned char rx_timeout"

.SS "void(* send_func) (unsigned char *data, unsigned int len)"

.SS "unsigned char tx_buffer[\fBPACKET_MAX_PL_LEN\fP+6]"


.SH "Author"
.PP 
Generated automatically by Doxygen from the source code\&.
