.TH "ppm_config" 3 "Wed Sep 16 2015" "Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ppm_config \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <datatypes\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBppm_control_type\fP \fBctrl_type\fP"
.br
.ti -1c
.RI "float \fBpid_max_erpm\fP"
.br
.ti -1c
.RI "float \fBhyst\fP"
.br
.ti -1c
.RI "float \fBpulse_start\fP"
.br
.ti -1c
.RI "float \fBpulse_end\fP"
.br
.ti -1c
.RI "bool \fBmedian_filter\fP"
.br
.ti -1c
.RI "bool \fBsafe_start\fP"
.br
.ti -1c
.RI "float \fBrpm_lim_start\fP"
.br
.ti -1c
.RI "float \fBrpm_lim_end\fP"
.br
.ti -1c
.RI "bool \fBmulti_esc\fP"
.br
.ti -1c
.RI "bool \fBtc\fP"
.br
.ti -1c
.RI "float \fBtc_max_diff\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "\fBppm_control_type\fP ctrl_type"

.SS "float hyst"

.SS "bool median_filter"

.SS "bool multi_esc"

.SS "float pid_max_erpm"

.SS "float pulse_end"

.SS "float pulse_start"

.SS "float rpm_lim_end"

.SS "float rpm_lim_start"

.SS "bool safe_start"

.SS "bool tc"

.SS "float tc_max_diff"


.SH "Author"
.PP 
Generated automatically by Doxygen from the source code\&.
