.TH "servo_simple.c" 3 "Wed Sep 16 2015" "Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
servo_simple.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'servo_simple\&.h'\fP
.br
\fC#include 'ch\&.h'\fP
.br
\fC#include 'hal\&.h'\fP
.br
\fC#include 'hw\&.h'\fP
.br
\fC#include 'conf_general\&.h'\fP
.br
\fC#include 'stm32f4xx_conf\&.h'\fP
.br
\fC#include 'utils\&.h'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBTIM_CLOCK\fP   1000000"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define TIM_CLOCK   1000000"

.SH "Author"
.PP 
Generated automatically by Doxygen from the source code\&.
