.TH "SERVO" 3 "Wed Sep 16 2015" "Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SERVO \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <servo\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "volatile signed short \fBpos\fP"
.br
.ti -1c
.RI "volatile unsigned char \fBoffset\fP"
.br
.ti -1c
.RI "GPIO_TypeDef * \fBgpio\fP"
.br
.ti -1c
.RI "volatile unsigned int \fBpin\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "GPIO_TypeDef* gpio"

.SS "volatile unsigned char offset"

.SS "volatile unsigned int pin"

.SS "volatile signed short pos"


.SH "Author"
.PP 
Generated automatically by Doxygen from the source code\&.
