.TH "nrf/spi_sw.c" 3 "Wed Sep 16 2015" "Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
nrf/spi_sw.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'spi_sw\&.h'\fP
.br
\fC#include 'ch\&.h'\fP
.br
\fC#include 'hal\&.h'\fP
.br
\fC#include <stdbool\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBspi_sw_init\fP (void)"
.br
.ti -1c
.RI "void \fBspi_sw_transfer\fP (char *in_buf, const char *out_buf, int length)"
.br
.ti -1c
.RI "void \fBspi_sw_begin\fP (void)"
.br
.ti -1c
.RI "void \fBspi_sw_end\fP (void)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void spi_sw_begin (void)"

.SS "void spi_sw_end (void)"

.SS "void spi_sw_init (void)"

.SS "void spi_sw_transfer (char * in_buf, const char * out_buf, int length)"

.SH "Author"
.PP 
Generated automatically by Doxygen from the source code\&.
