.TH "stm32f4xx_conf.h" 3 "Wed Sep 16 2015" "Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
stm32f4xx_conf.h \- Library configuration file\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'stm32f4xx_adc\&.h'\fP
.br
\fC#include 'stm32f4xx_crc\&.h'\fP
.br
\fC#include 'stm32f4xx_cryp\&.h'\fP
.br
\fC#include 'stm32f4xx_dac\&.h'\fP
.br
\fC#include 'stm32f4xx_dbgmcu\&.h'\fP
.br
\fC#include 'stm32f4xx_dcmi\&.h'\fP
.br
\fC#include 'stm32f4xx_dma\&.h'\fP
.br
\fC#include 'stm32f4xx_exti\&.h'\fP
.br
\fC#include 'stm32f4xx_flash\&.h'\fP
.br
\fC#include 'stm32f4xx_fsmc\&.h'\fP
.br
\fC#include 'stm32f4xx_hash\&.h'\fP
.br
\fC#include 'stm32f4_gpio_af\&.h'\fP
.br
\fC#include 'stm32f4xx_i2c\&.h'\fP
.br
\fC#include 'stm32f4xx_iwdg\&.h'\fP
.br
\fC#include 'stm32f4xx_pwr\&.h'\fP
.br
\fC#include 'stm32f4xx_rcc\&.h'\fP
.br
\fC#include 'stm32f4xx_rng\&.h'\fP
.br
\fC#include 'stm32f4xx_rtc\&.h'\fP
.br
\fC#include 'stm32f4xx_sdio\&.h'\fP
.br
\fC#include 'stm32f4xx_spi\&.h'\fP
.br
\fC#include 'stm32f4xx_syscfg\&.h'\fP
.br
\fC#include 'stm32f4xx_tim\&.h'\fP
.br
\fC#include 'stm32f4xx_usart\&.h'\fP
.br
\fC#include 'stm32f4xx_wwdg\&.h'\fP
.br
\fC#include 'misc\&.h'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBassert_param\fP(expr)   ((void)0)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Library configuration file\&. 


.PP
\fBAuthor:\fP
.RS 4
MCD Application Team 
.RE
.PP
\fBVersion:\fP
.RS 4
V1\&.0\&.0 
.RE
.PP
\fBDate:\fP
.RS 4
19-September-2011 
.RE
.PP
\fBAttention:\fP
.RS 4
.RE
.PP
THE PRESENT FIRMWARE WHICH IS FOR GUIDANCE ONLY AIMS AT PROVIDING CUSTOMERS WITH CODING INFORMATION REGARDING THEIR PRODUCTS IN ORDER FOR THEM TO SAVE TIME\&. AS A RESULT, STMICROELECTRONICS SHALL NOT BE HELD LIABLE FOR ANY DIRECT, INDIRECT OR CONSEQUENTIAL DAMAGES WITH RESPECT TO ANY CLAIMS ARISING FROM THE CONTENT OF SUCH FIRMWARE AND/OR THE USE MADE BY CUSTOMERS OF THE CODING INFORMATION CONTAINED HEREIN IN CONNECTION WITH THEIR PRODUCTS\&.
.PP
.SS "(C) COPYRIGHT 2011 STMicroelectronics"

.SH "Macro Definition Documentation"
.PP 
.SS "#define assert_param(expr)   ((void)0)"

.SH "Author"
.PP 
Generated automatically by Doxygen from the source code\&.
