.TH "terminal.h" 3 "Wed Sep 16 2015" "Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
terminal.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'mcpwm\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBterminal_process_string\fP (char *str)"
.br
.ti -1c
.RI "void \fBterminal_add_fault_data\fP (\fBfault_data\fP *data)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void terminal_add_fault_data (\fBfault_data\fP * data)"

.SS "void terminal_process_string (char * str)"

.SH "Author"
.PP 
Generated automatically by Doxygen from the source code\&.
