.TH "timeout.h" 3 "Wed Sep 16 2015" "Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
timeout.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'chtypes\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBtimeout_init\fP (void)"
.br
.ti -1c
.RI "void \fBtimeout_configure\fP (systime_t timeout, float brake_current)"
.br
.ti -1c
.RI "void \fBtimeout_reset\fP (void)"
.br
.ti -1c
.RI "bool \fBtimeout_has_timeout\fP (void)"
.br
.ti -1c
.RI "systime_t \fBtimeout_get_timeout_msec\fP (void)"
.br
.ti -1c
.RI "float \fBtimeout_get_brake_current\fP (void)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void timeout_configure (systime_t timeout, float brake_current)"

.SS "float timeout_get_brake_current (void)"

.SS "systime_t timeout_get_timeout_msec (void)"

.SS "bool timeout_has_timeout (void)"

.SS "void timeout_init (void)"

.SS "void timeout_reset (void)"

.SH "Author"
.PP 
Generated automatically by Doxygen from the source code\&.
