.TH "ws2811.c" 3 "Wed Sep 16 2015" "Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ws2811.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <math\&.h>\fP
.br
\fC#include 'ws2811\&.h'\fP
.br
\fC#include 'stm32f4xx_conf\&.h'\fP
.br
\fC#include 'ch\&.h'\fP
.br
\fC#include 'hal\&.h'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBTIM_PERIOD\fP   (((168000000 / 2 / \fBWS2811_CLK_HZ\fP) \- 1))"
.br
.ti -1c
.RI "#define \fBLED_BUFFER_LEN\fP   (\fBWS2811_LED_NUM\fP + 1)"
.br
.ti -1c
.RI "#define \fBBITBUFFER_PAD\fP   50"
.br
.ti -1c
.RI "#define \fBBITBUFFER_LEN\fP   (24 * \fBLED_BUFFER_LEN\fP + \fBBITBUFFER_PAD\fP)"
.br
.ti -1c
.RI "#define \fBWS2811_ZERO\fP   (\fBTIM_PERIOD\fP * 0\&.2)"
.br
.ti -1c
.RI "#define \fBWS2811_ONE\fP   (\fBTIM_PERIOD\fP * 0\&.8)"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBws2811_init\fP (void)"
.br
.ti -1c
.RI "void \fBws2811_set_led_color\fP (int led, uint32_t color)"
.br
.ti -1c
.RI "uint32_t \fBws2811_get_led_color\fP (int led)"
.br
.ti -1c
.RI "void \fBws2811_all_off\fP (void)"
.br
.ti -1c
.RI "void \fBws2811_set_all\fP (uint32_t color)"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define BITBUFFER_LEN   (24 * \fBLED_BUFFER_LEN\fP + \fBBITBUFFER_PAD\fP)"

.SS "#define BITBUFFER_PAD   50"

.SS "#define LED_BUFFER_LEN   (\fBWS2811_LED_NUM\fP + 1)"

.SS "#define TIM_PERIOD   (((168000000 / 2 / \fBWS2811_CLK_HZ\fP) \- 1))"

.SS "#define WS2811_ONE   (\fBTIM_PERIOD\fP * 0\&.8)"

.SS "#define WS2811_ZERO   (\fBTIM_PERIOD\fP * 0\&.2)"

.SH "Function Documentation"
.PP 
.SS "void ws2811_all_off (void)"

.SS "uint32_t ws2811_get_led_color (int led)"

.SS "void ws2811_init (void)"

.SS "void ws2811_set_all (uint32_t color)"

.SS "void ws2811_set_led_color (int led, uint32_t color)"

.SH "Author"
.PP 
Generated automatically by Doxygen from the source code\&.
