.TH "ws2811.h" 3 "Wed Sep 16 2015" "Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ws2811.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <stdint\&.h>\fP
.br
\fC#include 'conf_general\&.h'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBCOLOR_BLACK\fP   0x000000"
.br
.ti -1c
.RI "#define \fBCOLOR_WHITE\fP   0xFFFFFF"
.br
.ti -1c
.RI "#define \fBCOLOR_BLUE\fP   0x0000FF"
.br
.ti -1c
.RI "#define \fBCOLOR_GREEN\fP   0x00FF00"
.br
.ti -1c
.RI "#define \fBCOLOR_RED\fP   0xFF0000"
.br
.ti -1c
.RI "#define \fBCOLOR_NAVY\fP   0x000080"
.br
.ti -1c
.RI "#define \fBCOLOR_DARKBLUE\fP   0x00008B"
.br
.ti -1c
.RI "#define \fBCOLOR_DARKGREEN\fP   0x006400"
.br
.ti -1c
.RI "#define \fBCOLOR_DARKCYAN\fP   0x008B8B"
.br
.ti -1c
.RI "#define \fBCOLOR_CYAN\fP   0x00FFFF"
.br
.ti -1c
.RI "#define \fBCOLOR_TURQUOISE\fP   0x40E0D0"
.br
.ti -1c
.RI "#define \fBCOLOR_INDIGO\fP   0x4B0082"
.br
.ti -1c
.RI "#define \fBCOLOR_DARKRED\fP   0x800000"
.br
.ti -1c
.RI "#define \fBCOLOR_OLIVE\fP   0x808000"
.br
.ti -1c
.RI "#define \fBCOLOR_GRAY\fP   0x808080"
.br
.ti -1c
.RI "#define \fBCOLOR_SKYBLUE\fP   0x87CEEB"
.br
.ti -1c
.RI "#define \fBCOLOR_BLUEVIOLET\fP   0x8A2BE2"
.br
.ti -1c
.RI "#define \fBCOLOR_LIGHTGREEN\fP   0x90EE90"
.br
.ti -1c
.RI "#define \fBCOLOR_DARKVIOLET\fP   0x9400D3"
.br
.ti -1c
.RI "#define \fBCOLOR_YELLOWGREEN\fP   0x9ACD32"
.br
.ti -1c
.RI "#define \fBCOLOR_BROWN\fP   0xA52A2A"
.br
.ti -1c
.RI "#define \fBCOLOR_DARKGRAY\fP   0xA9A9A9"
.br
.ti -1c
.RI "#define \fBCOLOR_SIENNA\fP   0xA0522D"
.br
.ti -1c
.RI "#define \fBCOLOR_LIGHTBLUE\fP   0xADD8E6"
.br
.ti -1c
.RI "#define \fBCOLOR_GREENYELLOW\fP   0xADFF2F"
.br
.ti -1c
.RI "#define \fBCOLOR_SILVER\fP   0xC0C0C0"
.br
.ti -1c
.RI "#define \fBCOLOR_LIGHTGREY\fP   0xD3D3D3"
.br
.ti -1c
.RI "#define \fBCOLOR_LIGHTCYAN\fP   0xE0FFFF"
.br
.ti -1c
.RI "#define \fBCOLOR_VIOLET\fP   0xEE82EE"
.br
.ti -1c
.RI "#define \fBCOLOR_AZUR\fP   0xF0FFFF"
.br
.ti -1c
.RI "#define \fBCOLOR_BEIGE\fP   0xF5F5DC"
.br
.ti -1c
.RI "#define \fBCOLOR_MAGENTA\fP   0xFF00FF"
.br
.ti -1c
.RI "#define \fBCOLOR_TOMATO\fP   0xFF6347"
.br
.ti -1c
.RI "#define \fBCOLOR_GOLD\fP   0xFFD700"
.br
.ti -1c
.RI "#define \fBCOLOR_ORANGE\fP   0xFFA500"
.br
.ti -1c
.RI "#define \fBCOLOR_SNOW\fP   0xFFFAFA"
.br
.ti -1c
.RI "#define \fBCOLOR_YELLOW\fP   0xFFFF00"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBws2811_init\fP (void)"
.br
.ti -1c
.RI "void \fBws2811_set_led_color\fP (int led, uint32_t color)"
.br
.ti -1c
.RI "uint32_t \fBws2811_get_led_color\fP (int led)"
.br
.ti -1c
.RI "void \fBws2811_all_off\fP (void)"
.br
.ti -1c
.RI "void \fBws2811_set_all\fP (uint32_t color)"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define COLOR_AZUR   0xF0FFFF"

.SS "#define COLOR_BEIGE   0xF5F5DC"

.SS "#define COLOR_BLACK   0x000000"

.SS "#define COLOR_BLUE   0x0000FF"

.SS "#define COLOR_BLUEVIOLET   0x8A2BE2"

.SS "#define COLOR_BROWN   0xA52A2A"

.SS "#define COLOR_CYAN   0x00FFFF"

.SS "#define COLOR_DARKBLUE   0x00008B"

.SS "#define COLOR_DARKCYAN   0x008B8B"

.SS "#define COLOR_DARKGRAY   0xA9A9A9"

.SS "#define COLOR_DARKGREEN   0x006400"

.SS "#define COLOR_DARKRED   0x800000"

.SS "#define COLOR_DARKVIOLET   0x9400D3"

.SS "#define COLOR_GOLD   0xFFD700"

.SS "#define COLOR_GRAY   0x808080"

.SS "#define COLOR_GREEN   0x00FF00"

.SS "#define COLOR_GREENYELLOW   0xADFF2F"

.SS "#define COLOR_INDIGO   0x4B0082"

.SS "#define COLOR_LIGHTBLUE   0xADD8E6"

.SS "#define COLOR_LIGHTCYAN   0xE0FFFF"

.SS "#define COLOR_LIGHTGREEN   0x90EE90"

.SS "#define COLOR_LIGHTGREY   0xD3D3D3"

.SS "#define COLOR_MAGENTA   0xFF00FF"

.SS "#define COLOR_NAVY   0x000080"

.SS "#define COLOR_OLIVE   0x808000"

.SS "#define COLOR_ORANGE   0xFFA500"

.SS "#define COLOR_RED   0xFF0000"

.SS "#define COLOR_SIENNA   0xA0522D"

.SS "#define COLOR_SILVER   0xC0C0C0"

.SS "#define COLOR_SKYBLUE   0x87CEEB"

.SS "#define COLOR_SNOW   0xFFFAFA"

.SS "#define COLOR_TOMATO   0xFF6347"

.SS "#define COLOR_TURQUOISE   0x40E0D0"

.SS "#define COLOR_VIOLET   0xEE82EE"

.SS "#define COLOR_WHITE   0xFFFFFF"

.SS "#define COLOR_YELLOW   0xFFFF00"

.SS "#define COLOR_YELLOWGREEN   0x9ACD32"

.SH "Function Documentation"
.PP 
.SS "void ws2811_all_off (void)"

.SS "uint32_t ws2811_get_led_color (int led)"

.SS "void ws2811_init (void)"

.SS "void ws2811_set_all (uint32_t color)"

.SS "void ws2811_set_led_color (int led, uint32_t color)"

.SH "Author"
.PP 
Generated automatically by Doxygen from the source code\&.
