{ build32 ? false
, supportedSystems

, self
, nix-filter

, stdenv
, doxygen
}:

let
  makeTarget = if build32 then "all" else "all64";
  name = if build32 then "lbm" else "lbm64";
in stdenv.mkDerivation {
  pname = "lbm-c-doc";
  # IDK what pattern should be used to get ahold of the version number...
  version = self.shortRev or self.rev or self.dirtyShortRev or "unknown";
  
  meta = {
    description = "LispBM's autogenerated source code documentation";
    platforms = supportedSystems;
  };
  
  src = nix-filter {
    root = self;
    include = [
      "src"
      "include"
      "platform"
      "doc/c_doc/Makefile"
      "doc/c_doc/Doxyfile"
      "doc/c_doc/mainpage.dox"
    ];
  };
  
  buildPhase = ''
    cd doc/c_doc
    
    make all
  '';
  installPhase = ''
    mkdir -p $out
    
    cp -r html $out/
  '';
  
  nativeBuildInputs = [
    doxygen
  ];
}